#!/usr/bin/env python3
"""Package a verified checkout without credentials or installation data."""
import argparse
import hashlib
import json
import subprocess
import tarfile
import tempfile
from pathlib import Path
import shutil


def package(root, output):
    output.mkdir(parents=True, exist_ok=True)
    revision = subprocess.check_output(['git', 'rev-parse', 'HEAD'], cwd=root, text=True).strip()
    with tempfile.TemporaryDirectory() as temporary:
        stage = Path(temporary) / 'froststream'
        stage.mkdir()
        archive = Path(temporary) / 'source.tar'
        subprocess.run(['git', 'archive', '--format=tar', '-o', str(archive), 'HEAD'], cwd=root, check=True)
        with tarfile.open(archive) as source:
            source.extractall(stage, filter='data')
        # These are generated by the verified AppHost, with CI example values only.
        for mode in ('full', 'lite'):
            area = 'FullApp' if mode == 'full' else 'LiteApp'
            source = root / 'src/App' / area / 'docker-compose'
            target = stage / 'src/App' / area / source.name
            target.mkdir()
            shutil.copy2(source / 'docker-compose.yaml', target)
            public = {'LITE_DATABASE_PATH', 'LITE_BACKUP_DIRECTORY', 'LITE_KEYS_PATH',
                      'POSTGRES_USER', 'AUTHENTIK_CLIENT_ID', 'AUTHENTIK_BOOTSTRAP_EMAIL',
                      'AUTH_PUBLIC_ORIGIN', 'AUTH_AUTHORITY', 'FRONTEND_PUBLIC_ORIGIN',
                      'FRONTEND_PUBLIC_AUTH_AUTHORITY', 'AUTHENTIK_PUBLIC_AUTHORITY', 'CAST_ADVERTISED_BASE_URL'}
            lines = []
            for line in (source / '.env').read_text().splitlines():
                if '=' in line and not line.startswith('#'):
                    key, value = line.split('=', 1)
                    lines.append(key + '=' + (value if key in public else "'replace-before-installation'"))
            (target / '.env.example').write_text('\n'.join(lines) + '\n')
        # TLS private keys and vault recovery material are created on the installing host.
        forbidden = {'.env', 'aspire-development.env', 'init.env'}
        for path in list(stage.rglob('*')):
            if path.is_file() and (path.name in forbidden or path.suffix in ('.pem', '.key')):
                path.unlink()
        for guide in ('docs/DEPLOYMENT_PROFILES.md', 'docs/BACKUP_RESTORE.md'):
            if not (stage / guide).is_file():
                raise RuntimeError('Release revision is missing ' + guide)
        (stage / 'RELEASE.json').write_text(json.dumps({'revision': revision,
            'profiles': ['Full', 'Lite'], 'installation': 'docs/DEPLOYMENT_PROFILES.md',
            'recovery': 'docs/BACKUP_RESTORE.md'}, indent=2) + '\n')
        artifact = output / 'froststream-release.tar.gz'
        with tarfile.open(artifact, 'w:gz') as release:
            release.add(stage, arcname='froststream')
        (output / 'SHA256SUMS').write_text(hashlib.sha256(artifact.read_bytes()).hexdigest() + '  ' + artifact.name + '\n')
    print(f'Packaged revision {revision}: {artifact}')


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--output', type=Path, required=True)
    args = parser.parse_args()
    package(Path(__file__).resolve().parents[4], args.output.resolve())
