<Project Sdk="Aspire.AppHost.Sdk/13.5.3">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <UserSecretsId>eb53b053-b6b0-4511-a4ad-31ecfcbe9b3d</UserSecretsId>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        <AspireUseCliBundle>true</AspireUseCliBundle>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Aspire.Hosting.AppHost" />
      <PackageReference Include="Aspire.Hosting.Docker" />
      <PackageReference Include="Aspire.Hosting.JavaScript" />
      <PackageReference Include="Aspire.Hosting.Nats" />
      <PackageReference Include="Aspire.Hosting.PostgreSQL" />
      <PackageReference Include="CommunityToolkit.Aspire.Hosting.DbGate" />
      <PackageReference Include="CommunityToolkit.Aspire.Hosting.PostgreSQL.Extensions" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="configs\nats\certs\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\BackupService\BackupService.csproj" />
      <ProjectReference Include="..\DataBridge\DataBridge.csproj" />
      <ProjectReference Include="..\MediaProcessor\MediaProcessor.csproj" />
      <ProjectReference Include="..\Scheduler\Scheduler.csproj" />
      <ProjectReference Include="..\WebAPI\WebAPI.csproj" />
      <ProjectReference Include="..\Worker\Worker.csproj" />
      <ProjectReference Include="..\Deployment\Deployment.csproj" IsAspireProjectResource="false" />
    </ItemGroup>

</Project>
