#!/usr/bin/env python3
"""Regenerate the Phase 2a source inventory, or check it without changing files."""
import argparse
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OUTPUT = ROOT / 'SPLIT_PLAN/phase2-persistence-inventory.md'

def sources(directory):
    return sorted(p for p in (ROOT / directory).rglob('*.cs')
                  if not {'bin', 'obj', 'backups'} & set(p.relative_to(ROOT).parts))

def link(path):
    return f'[{path.name}](../{path.relative_to(ROOT).as_posix()})'

def generate():
    lines = ['# Phase 2 persistence source inventory', '',
             'Generated by `python3 SPLIT_PLAN/tools/persistence_inventory.py`. '
             'Run with `--check` to detect drift. This is a lexical source inventory, '
             'not a database schema dump; matches include comments and migration Down methods. '
             'Architecture decisions and interpretation are in [phase2-persistence-architecture.md](phase2-persistence-architecture.md).', '',
             '## Shared entities', '', '| Source | Entity declarations |', '| --- | --- |']
    for p in sources('src/App/Shared/Database'):
        entities = re.findall(r'\b(?:class|record)\s+(\w+Entity)\b', p.read_text())
        lines.append(f"| {link(p)} | {', '.join(f'`{e}`' for e in entities)} |")
    lines += ['', '## EF configuration and provider mappings', '',
              'Shared configuration files are applied by `DataBridgeDbContext.ApplyConfigurationsFromAssembly`; the selected provider pass materializes logical type/default hints.', '',
              '| Source | Explicit table names (schema is specified in source) | Logical column types (provider hints) |', '| --- | --- | --- |']
    for p in sources('src/App/DataBridge/Data'):
        if not p.name.endswith('Configuration.cs'):
            continue
        s = p.read_text()
        tables = sorted(set(re.findall(r'ToTable\(\s*"([^"]+)"', s)))
        types = sorted(set(re.findall(r'Has(?:ColumnType|PersistenceType)\("([^"]+)"', s)))
        lines.append(f"| {link(p)} | {', '.join(f'`{v}`' for v in tables)} | {', '.join(f'`{v}`' for v in types)} |")
    lines += ['', '## Persistence contracts', '', '| Source |', '| --- |']
    for p in sources('src/App/DataBridge'):
        if re.search(r'\binterface\s+I\w*(?:Repository|Purger|ReadService|DocumentQuery)\b', p.read_text()):
            lines.append(f'| {link(p)} |')
    patterns = {
        'SQLite': r'\bSqlite(?:Connection|Transaction|ConnectionFactory|SchemaInitializer)\b',
        'Npgsql': r'\bNpgsql(?:DataSourceBuilder|DataSource|Connection|Command|Transaction|DataReader|DbType)\b|using Npgsql;',
        'EF SQL': r'ExecuteSql\w*|FromSql\w*|\.SqlQuery\b',
        'transaction': r'BeginTransaction\w*|GetDbTransaction',
        'upsert': r'ON CONFLICT',
        'row lock': r'FOR UPDATE|SKIP LOCKED|pg_advisory',
        'array parameter': r'ANY\s*\(',
        'query dialect': r'ILIKE|DISTINCT ON|jsonb_|json_agg|::\w+|date_trunc|FILTER\s*\(',
        'unbounded timeout': r'CommandTimeout\s*=\s*0',
        'set update/delete': r'ExecuteUpdate\w*|ExecuteDelete\w*',
    }
    lines += ['', '## Runtime SQL and provider coupling across application modules', '',
              'Migration files are listed separately. Registration and reader helpers are included. '
              'Feature names flag source review work; absence of a flag does not prove portability.', '',
              '| Source | Observed features |', '| --- | --- |']
    for p in sources('src/App'):
        if 'Migrations' in p.parts:
            continue
        s = p.read_text()
        flags = [name for name, pattern in patterns.items() if re.search(pattern, s)]
        if flags:
            lines.append(f"| {link(p)} | {', '.join(flags)} |")
    lines += ['', '## PostgreSQL migration history', '',
              'Full uses FluentMigrator, not EF migrations. The list records source history, '
              'not versions applied to a running installation. Cleipnir owns its runtime table DDL separately.', '',
              '| Version | Source | Description | Transaction |', '| --- | --- | --- | --- |']
    versions = []
    for p in sources('src/App/DataBridge/Migrations/FluentMigrator'):
        s = p.read_text()
        m = re.search(r'\[Migration\((\d+),\s*(TransactionBehavior.None,\s*)?"([^"]+)"\)\]', s)
        if not m:
            raise ValueError(f'Unrecognized migration attribute: {p}')
        version, no_transaction, description = m.groups()
        versions.append(int(version))
        lines.append(f'| {version} | {link(p)} | {description} | {"None" if no_transaction else "Default"} |')
    if sorted(versions) != list(range(1, 98)):
        raise ValueError('Migration history changed; review the baseline cutoff and expected version range')
    lines += ['', 'Source history contains 97 distinct consecutive versions (1–97).', '']
    return '\n'.join(lines)

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    content = generate()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text() != content:
            parser.exit(1, 'Persistence inventory is stale; regenerate and review it.\n')
        print('Persistence inventory matches application sources; migrations 1–97 verified.')
    else:
        OUTPUT.write_text(content)
        print(f'Wrote {OUTPUT.relative_to(ROOT)}')
