#!/usr/bin/env python3
"""Build/check the reviewed SQLite v1 DDL from the PostgreSQL M097 catalog manifest."""
import argparse
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SCHEMA = ROOT / 'src/App/SharedApp/DataBridge/Persistence/Sqlite/Schema'
NOW = "(CAST(strftime('%s', 'now') AS INTEGER) * 1000000 + CAST(substr(strftime('%f', 'now'), 4, 3) AS INTEGER) * 1000)"

def quote(value):
    return '"' + value.replace('"', '""') + '"'

def literal(value):
    return "'" + value.replace("'", "''") + "'"

def table_name(schema, name):
    return schema + '_' + name

def check_sql(constraint):
    name, sql = constraint['name'], constraint['definition']
    if name.endswith('_key_format'):
        if sql != "CHECK (((key)::text ~ '^[a-z0-9-]{2,100}$'::text))":
            raise ValueError(f'Changed key constraint: {name}: {sql}')
        return 'length("key") BETWEEN 2 AND 100 AND "key" NOT GLOB \'*[^a-z0-9-]*\''
    if name.endswith('_worker_tag_format'):
        if sql != "CHECK (((worker_tag IS NULL) OR ((worker_tag)::text ~ '^[a-z0-9-]{2,50}$'::text)))":
            raise ValueError(f'Changed worker tag constraint: {name}: {sql}')
        return 'worker_tag IS NULL OR (length(worker_tag) BETWEEN 2 AND 50 AND worker_tag NOT GLOB \'*[^a-z0-9-]*\')'
    if name == 'ck_access_policy_assignments_type':
        return "principal_type IN ('user', 'group')"
    if name == 'ck_access_policy_providers_normalized':
        # PostgreSQL btrim's default removes ASCII spaces, like SQLite trim.
        return "provider <> '' AND provider = lower(trim(provider))"
    sql = sql.removeprefix('CHECK (')[:-1]
    sql = sql.replace('::double precision', '')
    if re.search(r'::|~|ANY|ARRAY|btrim', sql):
        raise ValueError(f'Unreviewed PostgreSQL check: {name}: {sql}')
    return sql

def default_sql(column):
    value = column['default']
    if value is None or column['identity']:
        return None
    if value in ('now()', "(now() AT TIME ZONE 'UTC'::text)"):
        return NOW
    if value in ('true', 'false'):
        return '1' if value == 'true' else '0'
    if re.fullmatch(r'-?\d+(\.\d+)?', value):
        return value
    if re.fullmatch(r"'(?:[^']|'')*'::[a-zA-Z_. ]+", value):
        return value.split('::', 1)[0]
    raise ValueError(f'Unreviewed default: {value}')

def generate(manifest):
    if manifest['postgresMigrationVersion'] != 97:
        raise ValueError('Baseline v1 cutoff is PostgreSQL migration 97')
    lines = ['-- SQLite application baseline v1, derived from a fresh PostgreSQL database at M097.',
             '-- Generated by SPLIT_PLAN/tools/sqlite_baseline.py; review translations before shipping.',
             '-- Application history is managed transactionally by SqliteSchemaInitializer.',
             '-- Cleipnir runtime tables are intentionally excluded.', '']
    for table in manifest['tables']:
        name = table_name(table['schema'], table['name'])
        primary = [c for c in table['constraints'] if c['kind'] == 'p']
        if len(primary) != 1:
            raise ValueError(f'Expected one primary key: {name}')
        pk = primary[0]
        definitions = []
        identity = None
        for col in table['columns']:
            name_sql = quote(col['name'])
            typ = col['type']
            if typ in ('integer', 'bigint', 'boolean', 'timestamp with time zone', 'timestamp without time zone'):
                storage_type = 'INTEGER'
            elif typ == 'double precision':
                storage_type = 'REAL'
            elif typ in ('text', 'uuid', 'jsonb', 'date') or typ.startswith('character varying') or typ in manifest['enums']:
                storage_type = 'TEXT'
            else:
                raise ValueError(f'Unreviewed type: {typ}')
            definition = f'{name_sql} {storage_type}'
            if col['identity']:
                if pk['columns'] != [col['name']] or storage_type != 'INTEGER':
                    raise ValueError(f'Unsupported identity: {name}.{col["name"]}')
                definition += ' PRIMARY KEY AUTOINCREMENT'
                identity = col['name']
            if not col['nullable']:
                definition += ' NOT NULL'
            default = default_sql(col)
            if default is not None:
                definition += ' DEFAULT ' + default
            checks = []
            if typ == 'boolean':
                checks.append(f'{name_sql} IN (0, 1)')
            if typ in manifest['enums']:
                checks.append(f'{name_sql} IN ({", ".join(map(literal, manifest["enums"][typ]))})')
            if typ == 'uuid':
                checks.append(f"length({name_sql}) = 32 AND {name_sql} NOT GLOB '*[^0-9a-f]*'")
            if typ == 'jsonb':
                checks.append(f'json_valid({name_sql})')
            length = re.fullmatch(r'character varying\((\d+)\)', typ)
            if length:
                checks.append(f'length({name_sql}) <= {length[1]}')
            if checks:
                definition += f' CHECK ({name_sql} IS NULL OR ({" AND ".join(checks)}))'
            definitions.append(definition)
        if identity is None:
            definitions.append(f'CONSTRAINT {quote(table_name(table["schema"], pk["name"]))} PRIMARY KEY ({", ".join(map(quote, pk["columns"]))})')
        actions = {'a': 'NO ACTION', 'r': 'RESTRICT', 'c': 'CASCADE', 'n': 'SET NULL', 'd': 'SET DEFAULT'}
        for constraint in table['constraints']:
            prefix = 'CONSTRAINT ' + quote(table_name(table['schema'], constraint['name']))
            if constraint['kind'] == 'f':
                if 'DEFERRABLE' in constraint['definition'] or 'MATCH FULL' in constraint['definition']:
                    raise ValueError('Unreviewed foreign key: ' + constraint['definition'])
                definitions.append(f'{prefix} FOREIGN KEY ({", ".join(map(quote, constraint["columns"]))}) '
                                   f'REFERENCES {quote(table_name(constraint["targetSchema"], constraint["targetTable"]))} '
                                   f'({", ".join(map(quote, constraint["targetColumns"]))}) '
                                   f'ON UPDATE {actions[constraint["onUpdate"]]} ON DELETE {actions[constraint["onDelete"]]}')
            elif constraint['kind'] == 'c':
                definitions.append(f'{prefix} CHECK ({check_sql(constraint)})')
            elif constraint['kind'] not in ('p', 'u', 'n'):
                raise ValueError('Unsupported constraint: ' + constraint['definition'])
        lines += [f'CREATE TABLE {quote(name)} (', '    ' + ',\n    '.join(definitions), ');', '']
    # Non-primary unique indexes also implement PostgreSQL UNIQUE constraints. SQLite FKs can
    # reference these indexes; avoid duplicating UNIQUE constraints with additional autoindexes.
    for table in manifest['tables']:
        for index in table['indexes']:
            if index['primary']:
                continue
            columns = []
            for col in index['columns']:
                col = re.sub(r'lower\(\(?([a-z_]+)\)?::text\)', r'lower(\1)', col)
                if '::' in col or not re.fullmatch(r'(?:"?\w+"?(?: (?:ASC|DESC))?|lower\(\w+\))', col):
                    raise ValueError('Unreviewed index expression: ' + col)
                columns.append(col)
            sql = f'CREATE {"UNIQUE " if index["unique"] else ""}INDEX {quote(table_name(table["schema"], index["name"]))} ON {quote(table_name(table["schema"], table["name"]))} ({", ".join(columns)})'
            if index['predicate']:
                predicate = index['predicate'].replace('true', '1').replace('false', '0')
                if '::' in predicate:
                    raise ValueError('Unreviewed index predicate: ' + predicate)
                sql += ' WHERE ' + predicate
            lines.append(sql + ';')
    return '\n'.join(lines) + '\n'

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    result = generate(json.loads((SCHEMA / 'postgres-v97-manifest.json').read_text()))
    output = SCHEMA / '001-baseline.sql'
    if args.check:
        if not output.exists() or output.read_text() != result:
            parser.exit(1, 'SQLite baseline differs from reviewed manifest; regenerate and review.\n')
        print('SQLite baseline matches reviewed M097 manifest.')
    else:
        output.write_text(result)
        print(f'Wrote {output.relative_to(ROOT)}')
