-- SQLite application baseline v1, derived from a fresh PostgreSQL database at M097.
-- Generated by SPLIT_PLAN/tools/sqlite_baseline.py; review translations before shipping.
-- Application history is managed transactionally by SqliteSchemaInitializer.
-- Cleipnir runtime tables are intentionally excluded.

CREATE TABLE "auth_access_policies" (
    "policy_id" TEXT NOT NULL CHECK ("policy_id" IS NULL OR (length("policy_id") = 32 AND "policy_id" NOT GLOB '*[^0-9a-f]*')),
    "name" TEXT NOT NULL CHECK ("name" IS NULL OR (length("name") <= 200)),
    "description" TEXT CHECK ("description" IS NULL OR (length("description") <= 2000)),
    "enabled" INTEGER NOT NULL DEFAULT 1 CHECK ("enabled" IS NULL OR ("enabled" IN (0, 1))),
    "sync_status" TEXT NOT NULL DEFAULT 'pending' CHECK ("sync_status" IS NULL OR (length("sync_status") <= 32)),
    "sync_error" TEXT CHECK ("sync_error" IS NULL OR (length("sync_error") <= 2000)),
    "version" INTEGER NOT NULL DEFAULT 1,
    "created_at" INTEGER NOT NULL DEFAULT (CAST(strftime('%s', 'now') AS INTEGER) * 1000000 + CAST(substr(strftime('%f', 'now'), 4, 3) AS INTEGER) * 1000),
    "created_by_subject" TEXT CHECK ("created_by_subject" IS NULL OR (length("created_by_subject") <= 255)),
    "updated_at" INTEGER NOT NULL DEFAULT (CAST(strftime('%s', 'now') AS INTEGER) * 1000000 + CAST(substr(strftime('%f', 'now'), 4, 3) AS INTEGER) * 1000),
    "updated_by_subject" TEXT CHECK ("updated_by_subject" IS NULL OR (length("updated_by_subject") <= 255)),
    CONSTRAINT "auth_PK_access_policies" PRIMARY KEY ("policy_id")
);

CREATE TABLE "auth_access_policy_age_tiers" (
    "policy_id" TEXT NOT NULL CHECK ("policy_id" IS NULL OR (length("policy_id") = 32 AND "policy_id" NOT GLOB '*[^0-9a-f]*')),
    "minimum_age" INTEGER NOT NULL,
    CONSTRAINT "auth_pk_access_policy_age_tiers" PRIMARY KEY ("policy_id", "minimum_age"),
    CONSTRAINT "auth_ck_access_policy_age_tiers_nonnegative" CHECK ((minimum_age >= 0)),
    CONSTRAINT "auth_fk_access_policy_age_policy" FOREIGN KEY ("policy_id") REFERENCES "auth_access_policies" ("policy_id") ON UPDATE NO ACTION ON DELETE CASCADE
);

CREATE TABLE "auth_access_policy_assignments" (
    "policy_id" TEXT NOT NULL CHECK ("policy_id" IS NULL OR (length("policy_id") = 32 AND "policy_id" NOT GLOB '*[^0-9a-f]*')),
    "principal_type" TEXT NOT NULL CHECK ("principal_type" IS NULL OR (length("principal_type") <= 16)),
    "principal_id" TEXT NOT NULL CHECK ("principal_id" IS NULL OR (length("principal_id") <= 255)),
    CONSTRAINT "auth_pk_access_policy_assignments" PRIMARY KEY ("policy_id", "principal_type", "principal_id"),
    CONSTRAINT "auth_ck_access_policy_assignments_type" CHECK (principal_type IN ('user', 'group')),
    CONSTRAINT "auth_fk_access_policy_assignments_policy" FOREIGN KEY ("policy_id") REFERENCES "auth_access_policies" ("policy_id") ON UPDATE NO ACTION ON DELETE CASCADE
);

CREATE TABLE "auth_access_policy_bundles" (
    "policy_id" TEXT NOT NULL CHECK ("policy_id" IS NULL OR (length("policy_id") = 32 AND "policy_id" NOT GLOB '*[^0-9a-f]*')),
    "bundle_id" TEXT NOT NULL CHECK ("bundle_id" IS NULL OR (length("bundle_id") <= 255)),
    CONSTRAINT "auth_pk_access_policy_bundles" PRIMARY KEY ("policy_id", "bundle_id"),
    CONSTRAINT "auth_fk_access_policy_bundles_policy" FOREIGN KEY ("policy_id") REFERENCES "auth_access_policies" ("policy_id") ON UPDATE NO ACTION ON DELETE CASCADE
);

CREATE TABLE "auth_access_policy_media" (
    "policy_id" TEXT NOT NULL CHECK ("policy_id" IS NULL OR (length("policy_id") = 32 AND "policy_id" NOT GLOB '*[^0-9a-f]*')),
    "media_guid" TEXT NOT NULL CHECK ("media_guid" IS NULL OR (length("media_guid") = 32 AND "media_guid" NOT GLOB '*[^0-9a-f]*')),
    CONSTRAINT "auth_pk_access_policy_media" PRIMARY KEY ("policy_id", "media_guid"),
    CONSTRAINT "auth_fk_access_policy_media_policy" FOREIGN KEY ("policy_id") REFERENCES "auth_access_policies" ("policy_id") ON UPDATE NO ACTION ON DELETE CASCADE
);

CREATE TABLE "auth_access_policy_providers" (
    "policy_id" TEXT NOT NULL CHECK ("policy_id" IS NULL OR (length("policy_id") = 32 AND "policy_id" NOT GLOB '*[^0-9a-f]*')),
    "provider" TEXT NOT NULL CHECK ("provider" IS NULL OR (length("provider") <= 255)),
    CONSTRAINT "auth_pk_access_policy_providers" PRIMARY KEY ("policy_id", "provider"),
    CONSTRAINT "auth_ck_access_policy_providers_normalized" CHECK (provider <> '' AND provider = lower(trim(provider))),
    CONSTRAINT "auth_fk_access_policy_providers_policy" FOREIGN KEY ("policy_id") REFERENCES "auth_access_policies" ("policy_id") ON UPDATE NO ACTION ON DELETE CASCADE
);

CREATE TABLE "auth_cookie_profiles" (
    "id" TEXT NOT NULL CHECK ("id" IS NULL OR (length("id") = 32 AND "id" NOT GLOB '*[^0-9a-f]*')),
    "owner_subject" TEXT NOT NULL CHECK ("owner_subject" IS NULL OR (length("owner_subject") <= 255)),
    "profile_key" TEXT NOT NULL CHECK ("profile_key" IS NULL OR (length("profile_key") <= 100)),
    "site" TEXT CHECK ("site" IS NULL OR (length("site") <= 255)),
    "display_name" TEXT CHECK ("display_name" IS NULL OR (length("display_name") <= 255)),
    "created_at" INTEGER NOT NULL DEFAULT (CAST(strftime('%s', 'now') AS INTEGER) * 1000000 + CAST(substr(strftime('%f', 'now'), 4, 3) AS INTEGER) * 1000),
    "last_updated" INTEGER,
    CONSTRAINT "auth_PK_cookie_profiles" PRIMARY KEY ("id")
);

CREATE TABLE "auth_froststream_users" (
    "id" TEXT NOT NULL CHECK ("id" IS NULL OR (length("id") = 32 AND "id" NOT GLOB '*[^0-9a-f]*')),
    "authentik_subject_id" TEXT NOT NULL CHECK ("authentik_subject_id" IS NULL OR (length("authentik_subject_id") <= 255)),
    "display_name" TEXT NOT NULL CHECK ("display_name" IS NULL OR (length("display_name") <= 255)),
    "last_seen_at" INTEGER,
    "preferences" TEXT CHECK ("preferences" IS NULL OR (json_valid("preferences"))),
    "created_at" INTEGER NOT NULL DEFAULT (CAST(strftime('%s', 'now') AS INTEGER) * 1000000 + CAST(substr(strftime('%f', 'now'), 4, 3) AS INTEGER) * 1000),
    "last_updated" INTEGER,
    CONSTRAINT "auth_PK_froststream_users" PRIMARY KEY ("id")
);

CREATE TABLE "discovery_creator_sources" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "platform" TEXT NOT NULL CHECK ("platform" IS NULL OR (length("platform") <= 50)),
    "source_type" TEXT NOT NULL CHECK ("source_type" IS NULL OR (length("source_type") <= 50)),
    "source_url" TEXT NOT NULL CHECK ("source_url" IS NULL OR (length("source_url") <= 4096)),
    "scan_enabled" INTEGER NOT NULL DEFAULT 1 CHECK ("scan_enabled" IS NULL OR ("scan_enabled" IN (0, 1))),
    "incremental_page_size" INTEGER NOT NULL DEFAULT 50,
    "consecutive_known_threshold" INTEGER NOT NULL DEFAULT 25,
    "full_rescan_interval_days" INTEGER NOT NULL DEFAULT 30,
    "metadata_refresh_window" INTEGER NOT NULL DEFAULT 25,
    "created_at" INTEGER NOT NULL DEFAULT (CAST(strftime('%s', 'now') AS INTEGER) * 1000000 + CAST(substr(strftime('%f', 'now'), 4, 3) AS INTEGER) * 1000),
    "last_updated" INTEGER,
    "update_check_interval_hours" INTEGER NOT NULL DEFAULT 6,
    "account_id" INTEGER,
    "config_set_owner_subject" TEXT CHECK ("config_set_owner_subject" IS NULL OR (length("config_set_owner_subject") <= 255)),
    "config_set_key" TEXT CHECK ("config_set_key" IS NULL OR (length("config_set_key") <= 100)),
    CONSTRAINT "discovery_ck_creator_sources_scan_settings_positive" CHECK (((incremental_page_size > 0) AND (consecutive_known_threshold > 0) AND (full_rescan_interval_days > 0) AND (metadata_refresh_window > 0))),
    CONSTRAINT "discovery_fk_creator_sources_account_id" FOREIGN KEY ("account_id") REFERENCES "metadata_accounts" ("id") ON UPDATE NO ACTION ON DELETE SET NULL
);

CREATE TABLE "discovery_discovered_media" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "creator_source_id" INTEGER NOT NULL,
    "platform" TEXT NOT NULL CHECK ("platform" IS NULL OR (length("platform") <= 50)),
    "extractor" TEXT NOT NULL CHECK ("extractor" IS NULL OR (length("extractor") <= 255)),
    "external_media_id" TEXT NOT NULL CHECK ("external_media_id" IS NULL OR (length("external_media_id") <= 512)),
    "canonical_url" TEXT NOT NULL CHECK ("canonical_url" IS NULL OR (length("canonical_url") <= 4096)),
    "title" TEXT CHECK ("title" IS NULL OR (length("title") <= 2048)),
    "duration_seconds" REAL,
    "thumbnail_url" TEXT CHECK ("thumbnail_url" IS NULL OR (length("thumbnail_url") <= 4096)),
    "live_status" TEXT CHECK ("live_status" IS NULL OR (length("live_status") <= 100)),
    "availability" TEXT CHECK ("availability" IS NULL OR (length("availability") <= 100)),
    "discovery_status" TEXT NOT NULL DEFAULT 'Discovered' CHECK ("discovery_status" IS NULL OR (length("discovery_status") <= 50)),
    "metadata_status" TEXT NOT NULL DEFAULT 'PendingEnrichment' CHECK ("metadata_status" IS NULL OR (length("metadata_status") <= 50)),
    "first_seen_at" INTEGER NOT NULL DEFAULT (CAST(strftime('%s', 'now') AS INTEGER) * 1000000 + CAST(substr(strftime('%f', 'now'), 4, 3) AS INTEGER) * 1000),
    "last_seen_at" INTEGER NOT NULL DEFAULT (CAST(strftime('%s', 'now') AS INTEGER) * 1000000 + CAST(substr(strftime('%f', 'now'), 4, 3) AS INTEGER) * 1000),
    "missed_full_scan_count" INTEGER NOT NULL DEFAULT 0,
    "last_changed_at" INTEGER,
    "last_enqueued_at" INTEGER,
    "last_updated" INTEGER,
    "ignored_keyword" TEXT CHECK ("ignored_keyword" IS NULL OR (length("ignored_keyword") <= 200)),
    CONSTRAINT "discovery_fk_discovered_media_creator_source_id" FOREIGN KEY ("creator_source_id") REFERENCES "discovery_creator_sources" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
);

CREATE TABLE "downloads_download_config_sets" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "owner_subject" TEXT NOT NULL CHECK ("owner_subject" IS NULL OR (length("owner_subject") <= 255)),
    "key" TEXT NOT NULL CHECK ("key" IS NULL OR (length("key") <= 100)),
    "name" TEXT NOT NULL CHECK ("name" IS NULL OR (length("name") <= 255)),
    "description" TEXT CHECK ("description" IS NULL OR (length("description") <= 2000)),
    "storage_key" TEXT CHECK ("storage_key" IS NULL OR (length("storage_key") <= 100)),
    "cookie_profile_key" TEXT CHECK ("cookie_profile_key" IS NULL OR (length("cookie_profile_key") <= 100)),
    "ytdlp_options_json" TEXT CHECK ("ytdlp_options_json" IS NULL OR (json_valid("ytdlp_options_json"))),
    "priority" INTEGER NOT NULL DEFAULT 0,
    "created_at" INTEGER NOT NULL DEFAULT (CAST(strftime('%s', 'now') AS INTEGER) * 1000000 + CAST(substr(strftime('%f', 'now'), 4, 3) AS INTEGER) * 1000),
    "updated_at" INTEGER NOT NULL DEFAULT (CAST(strftime('%s', 'now') AS INTEGER) * 1000000 + CAST(substr(strftime('%f', 'now'), 4, 3) AS INTEGER) * 1000),
    "ignore_keywords_json" TEXT CHECK ("ignore_keywords_json" IS NULL OR (json_valid("ignore_keywords_json"))),
    "worker_tag" TEXT CHECK ("worker_tag" IS NULL OR (length("worker_tag") <= 50)),
    CONSTRAINT "downloads_ck_download_config_sets_key_format" CHECK (length("key") BETWEEN 2 AND 100 AND "key" NOT GLOB '*[^a-z0-9-]*'),
    CONSTRAINT "downloads_ck_download_config_sets_worker_tag_format" CHECK (worker_tag IS NULL OR (length(worker_tag) BETWEEN 2 AND 50 AND worker_tag NOT GLOB '*[^a-z0-9-]*'))
);

CREATE TABLE "downloads_download_option_presets" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "key" TEXT NOT NULL CHECK ("key" IS NULL OR (length("key") <= 100)),
    "name" TEXT NOT NULL CHECK ("name" IS NULL OR (length("name") <= 255)),
    "description" TEXT CHECK ("description" IS NULL OR (length("description") <= 2000)),
    "ytdlp_options_json" TEXT NOT NULL CHECK ("ytdlp_options_json" IS NULL OR (json_valid("ytdlp_options_json"))),
    "created_at" INTEGER NOT NULL DEFAULT (CAST(strftime('%s', 'now') AS INTEGER) * 1000000 + CAST(substr(strftime('%f', 'now'), 4, 3) AS INTEGER) * 1000),
    "last_updated" INTEGER,
    CONSTRAINT "downloads_ck_download_option_presets_key_format" CHECK (length("key") BETWEEN 2 AND 100 AND "key" NOT GLOB '*[^a-z0-9-]*')
);

CREATE TABLE "imports_import_session_items" (
    "item_id" TEXT NOT NULL CHECK ("item_id" IS NULL OR (length("item_id") = 32 AND "item_id" NOT GLOB '*[^0-9a-f]*')),
    "session_id" TEXT NOT NULL CHECK ("session_id" IS NULL OR (length("session_id") = 32 AND "session_id" NOT GLOB '*[^0-9a-f]*')),
    "relative_path" TEXT NOT NULL CHECK ("relative_path" IS NULL OR (length("relative_path") <= 2048)),
    "file_name" TEXT NOT NULL CHECK ("file_name" IS NULL OR (length("file_name") <= 1024)),
    "file_size_bytes" INTEGER NOT NULL,
    "file_mtime" INTEGER,
    "sidecars" TEXT CHECK ("sidecars" IS NULL OR (json_valid("sidecars"))),
    "provider" TEXT CHECK ("provider" IS NULL OR (length("provider") <= 255)),
    "source_media_id" TEXT CHECK ("source_media_id" IS NULL OR (length("source_media_id") <= 512)),
    "source_url" TEXT CHECK ("source_url" IS NULL OR (length("source_url") <= 4096)),
    "title" TEXT CHECK ("title" IS NULL OR (length("title") <= 1024)),
    "probe_metadata" TEXT CHECK ("probe_metadata" IS NULL OR (json_valid("probe_metadata"))),
    "scan_metadata" TEXT CHECK ("scan_metadata" IS NULL OR (json_valid("scan_metadata"))),
    "enriched_metadata" TEXT CHECK ("enriched_metadata" IS NULL OR (json_valid("enriched_metadata"))),
    "user_metadata" TEXT CHECK ("user_metadata" IS NULL OR (json_valid("user_metadata"))),
    "metadata_state" TEXT NOT NULL CHECK ("metadata_state" IS NULL OR ("metadata_state" IN ('incomplete', 'ready', 'edited', 'placeholder_accepted'))),
    "excluded" INTEGER NOT NULL DEFAULT 0 CHECK ("excluded" IS NULL OR ("excluded" IN (0, 1))),
    "status" TEXT NOT NULL CHECK ("status" IS NULL OR ("status" IN ('discovered', 'probed', 'approved', 'hashing', 'uploading', 'finalizing', 'imported', 'already_imported', 'failed'))),
    "attempt" INTEGER NOT NULL DEFAULT 0,
    "content_hash_xxh128" TEXT CHECK ("content_hash_xxh128" IS NULL OR (length("content_hash_xxh128") <= 64)),
    "media_guid" TEXT CHECK ("media_guid" IS NULL OR (length("media_guid") = 32 AND "media_guid" NOT GLOB '*[^0-9a-f]*')),
    "storage_path" TEXT CHECK ("storage_path" IS NULL OR (length("storage_path") <= 2048)),
    "storage_version" TEXT CHECK ("storage_version" IS NULL OR (length("storage_version") <= 255)),
    "meta_storage_path" TEXT CHECK ("meta_storage_path" IS NULL OR (length("meta_storage_path") <= 2048)),
    "info_json_storage_path" TEXT CHECK ("info_json_storage_path" IS NULL OR (length("info_json_storage_path") <= 2048)),
    "thumbnail_storage_path" TEXT CHECK ("thumbnail_storage_path" IS NULL OR (length("thumbnail_storage_path") <= 2048)),
    "caption_storage_paths" TEXT CHECK ("caption_storage_paths" IS NULL OR (json_valid("caption_storage_paths"))),
    "error_code" TEXT CHECK ("error_code" IS NULL OR (length("error_code") <= 255)),
    "error_message" TEXT CHECK ("error_message" IS NULL OR (length("error_message") <= 4096)),
    "created_at" INTEGER NOT NULL DEFAULT (CAST(strftime('%s', 'now') AS INTEGER) * 1000000 + CAST(substr(strftime('%f', 'now'), 4, 3) AS INTEGER) * 1000),
    "updated_at" INTEGER NOT NULL DEFAULT (CAST(strftime('%s', 'now') AS INTEGER) * 1000000 + CAST(substr(strftime('%f', 'now'), 4, 3) AS INTEGER) * 1000),
    "completed_at" INTEGER,
    "metadata_source" TEXT NOT NULL DEFAULT 'Placeholder' CHECK ("metadata_source" IS NULL OR (length("metadata_source") <= 32)),
    "metadata_fetch_state" TEXT NOT NULL DEFAULT 'NotAttempted' CHECK ("metadata_fetch_state" IS NULL OR (length("metadata_fetch_state") <= 32)),
    "metadata_fetch_attempt" INTEGER NOT NULL DEFAULT 0,
    "metadata_fetch_message" TEXT CHECK ("metadata_fetch_message" IS NULL OR (length("metadata_fetch_message") <= 4096)),
    CONSTRAINT "imports_PK_import_session_items" PRIMARY KEY ("item_id"),
    CONSTRAINT "imports_fk_import_session_items_session_id" FOREIGN KEY ("session_id") REFERENCES "imports_import_sessions" ("session_id") ON UPDATE NO ACTION ON DELETE CASCADE
);

CREATE TABLE "imports_import_session_mappings" (
    "mapping_id" TEXT NOT NULL CHECK ("mapping_id" IS NULL OR (length("mapping_id") = 32 AND "mapping_id" NOT GLOB '*[^0-9a-f]*')),
    "session_id" TEXT NOT NULL CHECK ("session_id" IS NULL OR (length("session_id") = 32 AND "session_id" NOT GLOB '*[^0-9a-f]*')),
    "object_bucket" TEXT NOT NULL CHECK ("object_bucket" IS NULL OR (length("object_bucket") <= 255)),
    "object_key" TEXT NOT NULL CHECK ("object_key" IS NULL OR (length("object_key") <= 1024)),
    "format" TEXT NOT NULL CHECK ("format" IS NULL OR (length("format") <= 32)),
    "matched_count" INTEGER NOT NULL DEFAULT 0,
    "unmatched_count" INTEGER NOT NULL DEFAULT 0,
    "applied_at" INTEGER NOT NULL DEFAULT (CAST(strftime('%s', 'now') AS INTEGER) * 1000000 + CAST(substr(strftime('%f', 'now'), 4, 3) AS INTEGER) * 1000),
    CONSTRAINT "imports_PK_import_session_mappings" PRIMARY KEY ("mapping_id"),
    CONSTRAINT "imports_fk_import_session_mappings_session_id" FOREIGN KEY ("session_id") REFERENCES "imports_import_sessions" ("session_id") ON UPDATE NO ACTION ON DELETE CASCADE
);

CREATE TABLE "imports_import_sessions" (
    "session_id" TEXT NOT NULL CHECK ("session_id" IS NULL OR (length("session_id") = 32 AND "session_id" NOT GLOB '*[^0-9a-f]*')),
    "correlation_id" TEXT NOT NULL CHECK ("correlation_id" IS NULL OR (length("correlation_id") = 32 AND "correlation_id" NOT GLOB '*[^0-9a-f]*')),
    "status" TEXT NOT NULL CHECK ("status" IS NULL OR ("status" IN ('scanning', 'scan_failed', 'reviewing', 'committing', 'completed', 'completed_with_failures', 'cancelled'))),
    "source_kind" TEXT NOT NULL CHECK ("source_kind" IS NULL OR ("source_kind" IN ('worker_incoming', 'storage_backend'))),
    "source_root" TEXT NOT NULL CHECK ("source_root" IS NULL OR (length("source_root") <= 2048)),
    "sub_path" TEXT CHECK ("sub_path" IS NULL OR (length("sub_path") <= 2048)),
    "storage_key" TEXT NOT NULL CHECK ("storage_key" IS NULL OR (length("storage_key") <= 100)),
    "worker_tag" TEXT CHECK ("worker_tag" IS NULL OR (length("worker_tag") <= 128)),
    "requested_by" TEXT CHECK ("requested_by" IS NULL OR (length("requested_by") <= 255)),
    "total_items" INTEGER NOT NULL DEFAULT 0,
    "probed_items" INTEGER NOT NULL DEFAULT 0,
    "ready_items" INTEGER NOT NULL DEFAULT 0,
    "incomplete_items" INTEGER NOT NULL DEFAULT 0,
    "excluded_items" INTEGER NOT NULL DEFAULT 0,
    "approved_items" INTEGER NOT NULL DEFAULT 0,
    "imported_items" INTEGER NOT NULL DEFAULT 0,
    "already_imported_items" INTEGER NOT NULL DEFAULT 0,
    "failed_items" INTEGER NOT NULL DEFAULT 0,
    "max_parallel_items" INTEGER NOT NULL DEFAULT 6,
    "error_message" TEXT CHECK ("error_message" IS NULL OR (length("error_message") <= 4096)),
    "created_at" INTEGER NOT NULL DEFAULT (CAST(strftime('%s', 'now') AS INTEGER) * 1000000 + CAST(substr(strftime('%f', 'now'), 4, 3) AS INTEGER) * 1000),
    "updated_at" INTEGER NOT NULL DEFAULT (CAST(strftime('%s', 'now') AS INTEGER) * 1000000 + CAST(substr(strftime('%f', 'now'), 4, 3) AS INTEGER) * 1000),
    "completed_at" INTEGER,
    "delete_source_files" INTEGER NOT NULL DEFAULT 0 CHECK ("delete_source_files" IS NULL OR ("delete_source_files" IN (0, 1))),
    CONSTRAINT "imports_PK_import_sessions" PRIMARY KEY ("session_id")
);

CREATE TABLE "imports_local_import_batches" (
    "batch_id" TEXT NOT NULL CHECK ("batch_id" IS NULL OR (length("batch_id") = 32 AND "batch_id" NOT GLOB '*[^0-9a-f]*')),
    "correlation_id" TEXT NOT NULL CHECK ("correlation_id" IS NULL OR (length("correlation_id") = 32 AND "correlation_id" NOT GLOB '*[^0-9a-f]*')),
    "status" TEXT NOT NULL CHECK ("status" IS NULL OR ("status" IN ('queued', 'preparing', 'uploading', 'completed', 'already_imported', 'failed'))),
    "manifest_object_bucket" TEXT NOT NULL CHECK ("manifest_object_bucket" IS NULL OR (length("manifest_object_bucket") <= 255)),
    "manifest_object_key" TEXT NOT NULL CHECK ("manifest_object_key" IS NULL OR (length("manifest_object_key") <= 1024)),
    "source_root" TEXT NOT NULL CHECK ("source_root" IS NULL OR (length("source_root") <= 2048)),
    "storage_key" TEXT NOT NULL CHECK ("storage_key" IS NULL OR (length("storage_key") <= 100)),
    "requested_by" TEXT CHECK ("requested_by" IS NULL OR (length("requested_by") <= 255)),
    "requested_by_context" TEXT CHECK ("requested_by_context" IS NULL OR (length("requested_by_context") <= 255)),
    "total_items" INTEGER NOT NULL DEFAULT 0,
    "completed_items" INTEGER NOT NULL DEFAULT 0,
    "already_imported_items" INTEGER NOT NULL DEFAULT 0,
    "failed_items" INTEGER NOT NULL DEFAULT 0,
    "error_message" TEXT CHECK ("error_message" IS NULL OR (length("error_message") <= 4096)),
    "created_at" INTEGER NOT NULL DEFAULT (CAST(strftime('%s', 'now') AS INTEGER) * 1000000 + CAST(substr(strftime('%f', 'now'), 4, 3) AS INTEGER) * 1000),
    "updated_at" INTEGER NOT NULL DEFAULT (CAST(strftime('%s', 'now') AS INTEGER) * 1000000 + CAST(substr(strftime('%f', 'now'), 4, 3) AS INTEGER) * 1000),
    "completed_at" INTEGER,
    CONSTRAINT "imports_PK_local_import_batches" PRIMARY KEY ("batch_id")
);

CREATE TABLE "imports_local_import_items" (
    "item_id" TEXT NOT NULL CHECK ("item_id" IS NULL OR (length("item_id") = 32 AND "item_id" NOT GLOB '*[^0-9a-f]*')),
    "batch_id" TEXT NOT NULL CHECK ("batch_id" IS NULL OR (length("batch_id") = 32 AND "batch_id" NOT GLOB '*[^0-9a-f]*')),
    "item_index" INTEGER NOT NULL,
    "status" TEXT NOT NULL CHECK ("status" IS NULL OR ("status" IN ('queued', 'preparing', 'uploading', 'completed', 'already_imported', 'failed'))),
    "source_root" TEXT NOT NULL CHECK ("source_root" IS NULL OR (length("source_root") <= 2048)),
    "relative_path" TEXT NOT NULL CHECK ("relative_path" IS NULL OR (length("relative_path") <= 2048)),
    "storage_key" TEXT NOT NULL CHECK ("storage_key" IS NULL OR (length("storage_key") <= 100)),
    "provider" TEXT CHECK ("provider" IS NULL OR (length("provider") <= 255)),
    "source_media_id" TEXT CHECK ("source_media_id" IS NULL OR (length("source_media_id") <= 512)),
    "source_last_modified" INTEGER,
    "source_url" TEXT CHECK ("source_url" IS NULL OR (length("source_url") <= 4096)),
    "title" TEXT CHECK ("title" IS NULL OR (length("title") <= 1024)),
    "file_size_bytes" INTEGER,
    "content_hash_xxh128" TEXT CHECK ("content_hash_xxh128" IS NULL OR (length("content_hash_xxh128") <= 64)),
    "media_guid" TEXT CHECK ("media_guid" IS NULL OR (length("media_guid") = 32 AND "media_guid" NOT GLOB '*[^0-9a-f]*')),
    "storage_path" TEXT CHECK ("storage_path" IS NULL OR (length("storage_path") <= 2048)),
    "storage_version" TEXT CHECK ("storage_version" IS NULL OR (length("storage_version") <= 255)),
    "meta_storage_path" TEXT CHECK ("meta_storage_path" IS NULL OR (length("meta_storage_path") <= 2048)),
    "info_json_storage_path" TEXT CHECK ("info_json_storage_path" IS NULL OR (length("info_json_storage_path") <= 2048)),
    "thumbnail_storage_path" TEXT CHECK ("thumbnail_storage_path" IS NULL OR (length("thumbnail_storage_path") <= 2048)),
    "caption_storage_paths" TEXT CHECK ("caption_storage_paths" IS NULL OR (json_valid("caption_storage_paths"))),
    "error_code" TEXT CHECK ("error_code" IS NULL OR (length("error_code") <= 255)),
    "error_message" TEXT CHECK ("error_message" IS NULL OR (length("error_message") <= 4096)),
    "created_at" INTEGER NOT NULL DEFAULT (CAST(strftime('%s', 'now') AS INTEGER) * 1000000 + CAST(substr(strftime('%f', 'now'), 4, 3) AS INTEGER) * 1000),
    "updated_at" INTEGER NOT NULL DEFAULT (CAST(strftime('%s', 'now') AS INTEGER) * 1000000 + CAST(substr(strftime('%f', 'now'), 4, 3) AS INTEGER) * 1000),
    "completed_at" INTEGER,
    CONSTRAINT "imports_PK_local_import_items" PRIMARY KEY ("item_id"),
    CONSTRAINT "imports_fk_local_import_items_batch_id" FOREIGN KEY ("batch_id") REFERENCES "imports_local_import_batches" ("batch_id") ON UPDATE NO ACTION ON DELETE CASCADE
);

CREATE TABLE "jobs_creator_scan_state" (
    "creator_source_id" INTEGER NOT NULL,
    "last_successful_scan_at" INTEGER,
    "last_full_scan_at" INTEGER,
    "last_seen_high_watermark" TEXT CHECK ("last_seen_high_watermark" IS NULL OR (length("last_seen_high_watermark") <= 512)),
    "next_full_scan_start_index" INTEGER,
    "avatar_url" TEXT CHECK ("avatar_url" IS NULL OR (length("avatar_url") <= 4096)),
    "avatar_content_hash" TEXT CHECK ("avatar_content_hash" IS NULL OR (length("avatar_content_hash") <= 64)),
    "banner_url" TEXT CHECK ("banner_url" IS NULL OR (length("banner_url") <= 4096)),
    "banner_content_hash" TEXT CHECK ("banner_content_hash" IS NULL OR (length("banner_content_hash") <= 64)),
    "assets_last_refreshed_at" INTEGER,
    "assets_last_attempt_at" INTEGER,
    "assets_attempt_count" INTEGER NOT NULL DEFAULT 0,
    "assets_last_error" TEXT CHECK ("assets_last_error" IS NULL OR (length("assets_last_error") <= 2048)),
    CONSTRAINT "jobs_PK_creator_scan_state" PRIMARY KEY ("creator_source_id"),
    CONSTRAINT "jobs_ck_creator_scan_state_next_full_scan_start_index_positive" CHECK (((next_full_scan_start_index IS NULL) OR (next_full_scan_start_index > 0))),
    CONSTRAINT "jobs_fk_creator_scan_state_creator_source_id" FOREIGN KEY ("creator_source_id") REFERENCES "discovery_creator_sources" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
);

CREATE TABLE "jobs_download_artifacts" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "run_id" TEXT NOT NULL CHECK ("run_id" IS NULL OR (length("run_id") = 32 AND "run_id" NOT GLOB '*[^0-9a-f]*')),
    "job_id" TEXT NOT NULL CHECK ("job_id" IS NULL OR (length("job_id") = 32 AND "job_id" NOT GLOB '*[^0-9a-f]*')),
    "stage" TEXT NOT NULL CHECK ("stage" IS NULL OR ("stage" IN ('none', 'metadata', 'duplicate_check', 'waiting_for_worker', 'media_acquire', 'primary_media_upload', 'meta_sidecar_upload', 'info_json_upload', 'thumbnail_upload', 'caption_upload', 'rich_metadata_write', 'finalize', 'cleanup', 'compensation', 'live_chat_upload'))),
    "artifact_key" TEXT NOT NULL CHECK ("artifact_key" IS NULL OR (length("artifact_key") <= 512)),
    "kind" INTEGER NOT NULL,
    "required" INTEGER NOT NULL CHECK ("required" IS NULL OR ("required" IN (0, 1))),
    "status" TEXT NOT NULL CHECK ("status" IS NULL OR ("status" IN ('pending', 'uploading', 'stored', 'warning', 'failed', 'deleted', 'residual'))),
    "temp_file_ref" TEXT CHECK ("temp_file_ref" IS NULL OR (length("temp_file_ref") <= 2048)),
    "storage_key" TEXT CHECK ("storage_key" IS NULL OR (length("storage_key") <= 100)),
    "storage_path" TEXT CHECK ("storage_path" IS NULL OR (length("storage_path") <= 2048)),
    "storage_version" TEXT CHECK ("storage_version" IS NULL OR (length("storage_version") <= 255)),
    "content_hash_xxh128" TEXT CHECK ("content_hash_xxh128" IS NULL OR (length("content_hash_xxh128") <= 64)),
    "size_bytes" INTEGER,
    "warning_code" TEXT CHECK ("warning_code" IS NULL OR (length("warning_code") <= 255)),
    "warning_message" TEXT CHECK ("warning_message" IS NULL OR (length("warning_message") <= 4096)),
    "created_at" INTEGER NOT NULL DEFAULT (CAST(strftime('%s', 'now') AS INTEGER) * 1000000 + CAST(substr(strftime('%f', 'now'), 4, 3) AS INTEGER) * 1000),
    "updated_at" INTEGER NOT NULL DEFAULT (CAST(strftime('%s', 'now') AS INTEGER) * 1000000 + CAST(substr(strftime('%f', 'now'), 4, 3) AS INTEGER) * 1000),
    CONSTRAINT "jobs_fk_download_artifacts_run_id" FOREIGN KEY ("run_id") REFERENCES "jobs_download_job_runs" ("run_id") ON UPDATE NO ACTION ON DELETE CASCADE
);

CREATE TABLE "jobs_download_groups" (
    "group_id" TEXT NOT NULL CHECK ("group_id" IS NULL OR (length("group_id") = 32 AND "group_id" NOT GLOB '*[^0-9a-f]*')),
    "correlation_id" TEXT NOT NULL CHECK ("correlation_id" IS NULL OR (length("correlation_id") = 32 AND "correlation_id" NOT GLOB '*[^0-9a-f]*')),
    "kind" TEXT NOT NULL CHECK ("kind" IS NULL OR ("kind" IN ('direct', 'playlist', 'channel', 'creator_monitor'))),
    "status" TEXT NOT NULL CHECK ("status" IS NULL OR ("status" IN ('queued', 'expanding', 'running', 'stopping', 'stopped', 'completed', 'completed_with_warnings', 'completed_with_failures', 'failed'))),
    "source_url" TEXT NOT NULL CHECK ("source_url" IS NULL OR (length("source_url") <= 4096)),
    "requested_by" TEXT CHECK ("requested_by" IS NULL OR (length("requested_by") <= 255)),
    "storage_key" TEXT CHECK ("storage_key" IS NULL OR (length("storage_key") <= 100)),
    "total_jobs" INTEGER NOT NULL DEFAULT 0,
    "completed_jobs" INTEGER NOT NULL DEFAULT 0,
    "warning_jobs" INTEGER NOT NULL DEFAULT 0,
    "failed_jobs" INTEGER NOT NULL DEFAULT 0,
    "failure_code" TEXT CHECK ("failure_code" IS NULL OR (length("failure_code") <= 255)),
    "failure_message" TEXT CHECK ("failure_message" IS NULL OR (length("failure_message") <= 4096)),
    "created_at" INTEGER NOT NULL DEFAULT (CAST(strftime('%s', 'now') AS INTEGER) * 1000000 + CAST(substr(strftime('%f', 'now'), 4, 3) AS INTEGER) * 1000),
    "updated_at" INTEGER NOT NULL DEFAULT (CAST(strftime('%s', 'now') AS INTEGER) * 1000000 + CAST(substr(strftime('%f', 'now'), 4, 3) AS INTEGER) * 1000),
    "completed_at" INTEGER,
    CONSTRAINT "jobs_PK_download_groups" PRIMARY KEY ("group_id")
);

CREATE TABLE "jobs_download_job_history" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "job_id" TEXT NOT NULL CHECK ("job_id" IS NULL OR (length("job_id") = 32 AND "job_id" NOT GLOB '*[^0-9a-f]*')),
    "message_id" TEXT NOT NULL CHECK ("message_id" IS NULL OR (length("message_id") = 32 AND "message_id" NOT GLOB '*[^0-9a-f]*')),
    "operation_key" TEXT NOT NULL CHECK ("operation_key" IS NULL OR (length("operation_key") <= 512)),
    "event_name" TEXT NOT NULL CHECK ("event_name" IS NULL OR (length("event_name") <= 255)),
    "payload_json" TEXT CHECK ("payload_json" IS NULL OR (json_valid("payload_json"))),
    "recorded_at" INTEGER NOT NULL DEFAULT (CAST(strftime('%s', 'now') AS INTEGER) * 1000000 + CAST(substr(strftime('%f', 'now'), 4, 3) AS INTEGER) * 1000),
    CONSTRAINT "jobs_fk_download_job_history_job_id" FOREIGN KEY ("job_id") REFERENCES "jobs_download_jobs" ("job_id") ON UPDATE NO ACTION ON DELETE CASCADE
);

CREATE TABLE "jobs_download_job_progress_log" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "job_id" TEXT NOT NULL CHECK ("job_id" IS NULL OR (length("job_id") = 32 AND "job_id" NOT GLOB '*[^0-9a-f]*')),
    "sequence" INTEGER NOT NULL,
    "message" TEXT NOT NULL CHECK ("message" IS NULL OR (length("message") <= 2048)),
    "recorded_at" INTEGER NOT NULL DEFAULT (CAST(strftime('%s', 'now') AS INTEGER) * 1000000 + CAST(substr(strftime('%f', 'now'), 4, 3) AS INTEGER) * 1000),
    CONSTRAINT "jobs_fk_download_job_progress_log_job_id" FOREIGN KEY ("job_id") REFERENCES "jobs_download_jobs" ("job_id") ON UPDATE NO ACTION ON DELETE CASCADE
);

CREATE TABLE "jobs_download_job_runs" (
    "run_id" TEXT NOT NULL CHECK ("run_id" IS NULL OR (length("run_id") = 32 AND "run_id" NOT GLOB '*[^0-9a-f]*')),
    "job_id" TEXT NOT NULL CHECK ("job_id" IS NULL OR (length("job_id") = 32 AND "job_id" NOT GLOB '*[^0-9a-f]*')),
    "run_number" INTEGER NOT NULL,
    "status" TEXT NOT NULL CHECK ("status" IS NULL OR ("status" IN ('queued', 'running', 'stopping', 'stopped', 'compensating', 'completed', 'completed_with_warnings', 'failed', 'already_downloaded', 'ignored'))),
    "stage" TEXT NOT NULL CHECK ("stage" IS NULL OR ("stage" IN ('none', 'metadata', 'duplicate_check', 'waiting_for_worker', 'media_acquire', 'primary_media_upload', 'meta_sidecar_upload', 'info_json_upload', 'thumbnail_upload', 'caption_upload', 'rich_metadata_write', 'finalize', 'cleanup', 'compensation', 'live_chat_upload'))),
    "stage_status" TEXT NOT NULL CHECK ("stage_status" IS NULL OR ("stage_status" IN ('pending', 'running', 'retry_waiting', 'succeeded', 'skipped', 'warning', 'failed', 'stopped'))),
    "failure_kind" TEXT CHECK ("failure_kind" IS NULL OR ("failure_kind" IN ('unknown', 'transient', 'permanent', 'timeout', 'cancelled', 'interrupted', 'provider_blocked', 'stopped'))),
    "failure_code" TEXT CHECK ("failure_code" IS NULL OR (length("failure_code") <= 255)),
    "failure_message" TEXT CHECK ("failure_message" IS NULL OR (length("failure_message") <= 4096)),
    "created_at" INTEGER NOT NULL DEFAULT (CAST(strftime('%s', 'now') AS INTEGER) * 1000000 + CAST(substr(strftime('%f', 'now'), 4, 3) AS INTEGER) * 1000),
    "started_at" INTEGER,
    "updated_at" INTEGER NOT NULL DEFAULT (CAST(strftime('%s', 'now') AS INTEGER) * 1000000 + CAST(substr(strftime('%f', 'now'), 4, 3) AS INTEGER) * 1000),
    "ended_at" INTEGER,
    CONSTRAINT "jobs_PK_download_job_runs" PRIMARY KEY ("run_id"),
    CONSTRAINT "jobs_fk_download_job_runs_job_id" FOREIGN KEY ("job_id") REFERENCES "jobs_download_jobs" ("job_id") ON UPDATE NO ACTION ON DELETE CASCADE
);

CREATE TABLE "jobs_download_job_warnings" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "run_id" TEXT NOT NULL CHECK ("run_id" IS NULL OR (length("run_id") = 32 AND "run_id" NOT GLOB '*[^0-9a-f]*')),
    "job_id" TEXT NOT NULL CHECK ("job_id" IS NULL OR (length("job_id") = 32 AND "job_id" NOT GLOB '*[^0-9a-f]*')),
    "stage" TEXT NOT NULL CHECK ("stage" IS NULL OR ("stage" IN ('none', 'metadata', 'duplicate_check', 'waiting_for_worker', 'media_acquire', 'primary_media_upload', 'meta_sidecar_upload', 'info_json_upload', 'thumbnail_upload', 'caption_upload', 'rich_metadata_write', 'finalize', 'cleanup', 'compensation', 'live_chat_upload'))),
    "artifact_key" TEXT NOT NULL DEFAULT '' CHECK ("artifact_key" IS NULL OR (length("artifact_key") <= 512)),
    "warning_code" TEXT NOT NULL CHECK ("warning_code" IS NULL OR (length("warning_code") <= 255)),
    "warning_message" TEXT NOT NULL CHECK ("warning_message" IS NULL OR (length("warning_message") <= 4096)),
    "created_at" INTEGER NOT NULL DEFAULT (CAST(strftime('%s', 'now') AS INTEGER) * 1000000 + CAST(substr(strftime('%f', 'now'), 4, 3) AS INTEGER) * 1000),
    CONSTRAINT "jobs_fk_download_job_warnings_run_id" FOREIGN KEY ("run_id") REFERENCES "jobs_download_job_runs" ("run_id") ON UPDATE NO ACTION ON DELETE CASCADE
);

CREATE TABLE "jobs_download_jobs" (
    "job_id" TEXT NOT NULL CHECK ("job_id" IS NULL OR (length("job_id") = 32 AND "job_id" NOT GLOB '*[^0-9a-f]*')),
    "correlation_id" TEXT NOT NULL CHECK ("correlation_id" IS NULL OR (length("correlation_id") = 32 AND "correlation_id" NOT GLOB '*[^0-9a-f]*')),
    "state" TEXT NOT NULL CHECK ("state" IS NULL OR ("state" IN ('queued', 'metadata_pending', 'metadata_resolved', 'download_pending', 'downloaded_temp', 'upload_pending', 'uploaded', 'commit_pending', 'completed', 'compensating', 'failed_transient', 'failed_permanent', 'dead_lettered', 'already_downloaded', 'download_queued', 'cancelling', 'cancelled', 'ignored', 'provider_halted'))),
    "source_url" TEXT NOT NULL CHECK ("source_url" IS NULL OR (length("source_url") <= 4096)),
    "requested_by" TEXT CHECK ("requested_by" IS NULL OR (length("requested_by") <= 255)),
    "storage_key" TEXT CHECK ("storage_key" IS NULL OR (length("storage_key") <= 100)),
    "attempt_metadata" INTEGER NOT NULL DEFAULT 0,
    "attempt_download" INTEGER NOT NULL DEFAULT 0,
    "attempt_upload" INTEGER NOT NULL DEFAULT 0,
    "temp_file_ref" TEXT CHECK ("temp_file_ref" IS NULL OR (length("temp_file_ref") <= 2048)),
    "file_size_bytes" INTEGER,
    "content_hash_xxh128" TEXT CHECK ("content_hash_xxh128" IS NULL OR (length("content_hash_xxh128") <= 64)),
    "storage_version" TEXT CHECK ("storage_version" IS NULL OR (length("storage_version") <= 255)),
    "failure_kind" TEXT CHECK ("failure_kind" IS NULL OR ("failure_kind" IN ('unknown', 'transient', 'permanent', 'timeout', 'cancelled', 'interrupted', 'provider_blocked', 'stopped'))),
    "failure_code" TEXT CHECK ("failure_code" IS NULL OR (length("failure_code") <= 255)),
    "failure_message" TEXT CHECK ("failure_message" IS NULL OR (length("failure_message") <= 4096)),
    "created_at" INTEGER NOT NULL DEFAULT (CAST(strftime('%s', 'now') AS INTEGER) * 1000000 + CAST(substr(strftime('%f', 'now'), 4, 3) AS INTEGER) * 1000),
    "updated_at" INTEGER NOT NULL DEFAULT (CAST(strftime('%s', 'now') AS INTEGER) * 1000000 + CAST(substr(strftime('%f', 'now'), 4, 3) AS INTEGER) * 1000),
    "completed_at" INTEGER,
    "info_json_storage_path" TEXT CHECK ("info_json_storage_path" IS NULL OR (length("info_json_storage_path") <= 2048)),
    "info_json_content_hash_xxh128" TEXT CHECK ("info_json_content_hash_xxh128" IS NULL OR (length("info_json_content_hash_xxh128") <= 64)),
    "info_json_size_bytes" INTEGER,
    "meta_storage_path" TEXT CHECK ("meta_storage_path" IS NULL OR (length("meta_storage_path") <= 2048)),
    "priority" INTEGER NOT NULL DEFAULT 0,
    "ingest_origin" TEXT NOT NULL DEFAULT 'download' CHECK ("ingest_origin" IS NULL OR ("ingest_origin" IN ('download', 'local_import'))),
    "ignored_keyword" TEXT CHECK ("ignored_keyword" IS NULL OR (length("ignored_keyword") <= 200)),
    "source_kind" INTEGER NOT NULL DEFAULT 0,
    "status" TEXT NOT NULL DEFAULT 'queued' CHECK ("status" IS NULL OR ("status" IN ('queued', 'running', 'stopping', 'stopped', 'compensating', 'completed', 'completed_with_warnings', 'failed', 'already_downloaded', 'ignored'))),
    "stage" TEXT NOT NULL DEFAULT 'none' CHECK ("stage" IS NULL OR ("stage" IN ('none', 'metadata', 'duplicate_check', 'waiting_for_worker', 'media_acquire', 'primary_media_upload', 'meta_sidecar_upload', 'info_json_upload', 'thumbnail_upload', 'caption_upload', 'rich_metadata_write', 'finalize', 'cleanup', 'compensation', 'live_chat_upload'))),
    "stage_status" TEXT NOT NULL DEFAULT 'pending' CHECK ("stage_status" IS NULL OR ("stage_status" IN ('pending', 'running', 'retry_waiting', 'succeeded', 'skipped', 'warning', 'failed', 'stopped'))),
    "current_run_id" TEXT CHECK ("current_run_id" IS NULL OR (length("current_run_id") = 32 AND "current_run_id" NOT GLOB '*[^0-9a-f]*')),
    "current_run_number" INTEGER NOT NULL DEFAULT 0,
    "current_attempt" INTEGER NOT NULL DEFAULT 0,
    "current_artifact_key" TEXT CHECK ("current_artifact_key" IS NULL OR (length("current_artifact_key") <= 512)),
    "warning_count" INTEGER NOT NULL DEFAULT 0,
    "stop_requested_at" INTEGER,
    "stop_requested_by" TEXT CHECK ("stop_requested_by" IS NULL OR (length("stop_requested_by") <= 255)),
    "stop_reason" TEXT CHECK ("stop_reason" IS NULL OR (length("stop_reason") <= 512)),
    CONSTRAINT "jobs_PK_download_jobs" PRIMARY KEY ("job_id")
);

CREATE TABLE "jobs_download_provider_circuits" (
    "provider" TEXT NOT NULL CHECK ("provider" IS NULL OR (length("provider") <= 255)),
    "is_open" INTEGER NOT NULL CHECK ("is_open" IS NULL OR ("is_open" IN (0, 1))),
    "reason" TEXT CHECK ("reason" IS NULL OR (length("reason") <= 4096)),
    "opened_at" INTEGER,
    "cleared_at" INTEGER,
    CONSTRAINT "jobs_PK_download_provider_circuits" PRIMARY KEY ("provider")
);

CREATE TABLE "jobs_download_stage_attempts" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "run_id" TEXT NOT NULL CHECK ("run_id" IS NULL OR (length("run_id") = 32 AND "run_id" NOT GLOB '*[^0-9a-f]*')),
    "job_id" TEXT NOT NULL CHECK ("job_id" IS NULL OR (length("job_id") = 32 AND "job_id" NOT GLOB '*[^0-9a-f]*')),
    "stage" TEXT NOT NULL CHECK ("stage" IS NULL OR ("stage" IN ('none', 'metadata', 'duplicate_check', 'waiting_for_worker', 'media_acquire', 'primary_media_upload', 'meta_sidecar_upload', 'info_json_upload', 'thumbnail_upload', 'caption_upload', 'rich_metadata_write', 'finalize', 'cleanup', 'compensation', 'live_chat_upload'))),
    "artifact_key" TEXT NOT NULL DEFAULT '' CHECK ("artifact_key" IS NULL OR (length("artifact_key") <= 512)),
    "attempt" INTEGER NOT NULL,
    "status" TEXT NOT NULL CHECK ("status" IS NULL OR ("status" IN ('pending', 'running', 'retry_waiting', 'succeeded', 'skipped', 'warning', 'failed', 'stopped'))),
    "dispatch_id" TEXT NOT NULL CHECK ("dispatch_id" IS NULL OR (length("dispatch_id") = 32 AND "dispatch_id" NOT GLOB '*[^0-9a-f]*')),
    "operation_key" TEXT NOT NULL CHECK ("operation_key" IS NULL OR (length("operation_key") <= 512)),
    "failure_kind" TEXT CHECK ("failure_kind" IS NULL OR ("failure_kind" IN ('unknown', 'transient', 'permanent', 'timeout', 'cancelled', 'interrupted', 'provider_blocked', 'stopped'))),
    "failure_code" TEXT CHECK ("failure_code" IS NULL OR (length("failure_code") <= 255)),
    "failure_message" TEXT CHECK ("failure_message" IS NULL OR (length("failure_message") <= 4096)),
    "created_at" INTEGER NOT NULL DEFAULT (CAST(strftime('%s', 'now') AS INTEGER) * 1000000 + CAST(substr(strftime('%f', 'now'), 4, 3) AS INTEGER) * 1000),
    "started_at" INTEGER,
    "updated_at" INTEGER NOT NULL DEFAULT (CAST(strftime('%s', 'now') AS INTEGER) * 1000000 + CAST(substr(strftime('%f', 'now'), 4, 3) AS INTEGER) * 1000),
    "ended_at" INTEGER,
    CONSTRAINT "jobs_fk_download_stage_attempts_run_id" FOREIGN KEY ("run_id") REFERENCES "jobs_download_job_runs" ("run_id") ON UPDATE NO ACTION ON DELETE CASCADE
);

CREATE TABLE "jobs_download_worker_leases" (
    "dispatch_id" TEXT NOT NULL CHECK ("dispatch_id" IS NULL OR (length("dispatch_id") = 32 AND "dispatch_id" NOT GLOB '*[^0-9a-f]*')),
    "run_id" TEXT NOT NULL CHECK ("run_id" IS NULL OR (length("run_id") = 32 AND "run_id" NOT GLOB '*[^0-9a-f]*')),
    "job_id" TEXT NOT NULL CHECK ("job_id" IS NULL OR (length("job_id") = 32 AND "job_id" NOT GLOB '*[^0-9a-f]*')),
    "stage" TEXT NOT NULL CHECK ("stage" IS NULL OR ("stage" IN ('none', 'metadata', 'duplicate_check', 'waiting_for_worker', 'media_acquire', 'primary_media_upload', 'meta_sidecar_upload', 'info_json_upload', 'thumbnail_upload', 'caption_upload', 'rich_metadata_write', 'finalize', 'cleanup', 'compensation', 'live_chat_upload'))),
    "artifact_key" TEXT NOT NULL DEFAULT '' CHECK ("artifact_key" IS NULL OR (length("artifact_key") <= 512)),
    "attempt" INTEGER NOT NULL,
    "worker_instance_id" TEXT NOT NULL CHECK ("worker_instance_id" IS NULL OR (length("worker_instance_id") <= 255)),
    "status" TEXT NOT NULL CHECK ("status" IS NULL OR ("status" IN ('active', 'released', 'expired', 'rejected', 'stopped'))),
    "acquired_at" INTEGER NOT NULL,
    "last_heartbeat_at" INTEGER NOT NULL,
    "expires_at" INTEGER NOT NULL,
    "released_at" INTEGER,
    CONSTRAINT "jobs_PK_download_worker_leases" PRIMARY KEY ("dispatch_id"),
    CONSTRAINT "jobs_fk_download_worker_leases_run_id" FOREIGN KEY ("run_id") REFERENCES "jobs_download_job_runs" ("run_id") ON UPDATE NO ACTION ON DELETE CASCADE
);

CREATE TABLE "jobs_failed_download_jobs" (
    "job_id" TEXT NOT NULL CHECK ("job_id" IS NULL OR (length("job_id") = 32 AND "job_id" NOT GLOB '*[^0-9a-f]*')),
    "correlation_id" TEXT NOT NULL CHECK ("correlation_id" IS NULL OR (length("correlation_id") = 32 AND "correlation_id" NOT GLOB '*[^0-9a-f]*')),
    "failed_state" TEXT NOT NULL CHECK ("failed_state" IS NULL OR ("failed_state" IN ('queued', 'metadata_pending', 'metadata_resolved', 'download_pending', 'downloaded_temp', 'upload_pending', 'uploaded', 'commit_pending', 'completed', 'compensating', 'failed_transient', 'failed_permanent', 'dead_lettered', 'already_downloaded', 'download_queued', 'cancelling', 'cancelled', 'ignored', 'provider_halted'))),
    "failure_kind" TEXT NOT NULL CHECK ("failure_kind" IS NULL OR ("failure_kind" IN ('unknown', 'transient', 'permanent', 'timeout', 'cancelled', 'interrupted', 'provider_blocked', 'stopped'))),
    "failure_code" TEXT CHECK ("failure_code" IS NULL OR (length("failure_code") <= 255)),
    "failure_message" TEXT NOT NULL CHECK ("failure_message" IS NULL OR (length("failure_message") <= 4096)),
    "last_payload_json" TEXT CHECK ("last_payload_json" IS NULL OR (json_valid("last_payload_json"))),
    "failed_at" INTEGER NOT NULL DEFAULT (CAST(strftime('%s', 'now') AS INTEGER) * 1000000 + CAST(substr(strftime('%f', 'now'), 4, 3) AS INTEGER) * 1000),
    CONSTRAINT "jobs_PK_failed_download_jobs" PRIMARY KEY ("job_id")
);

CREATE TABLE "jobs_playlist_items" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "playlist_id" TEXT NOT NULL CHECK ("playlist_id" IS NULL OR (length("playlist_id") = 32 AND "playlist_id" NOT GLOB '*[^0-9a-f]*')),
    "job_id" TEXT NOT NULL CHECK ("job_id" IS NULL OR (length("job_id") = 32 AND "job_id" NOT GLOB '*[^0-9a-f]*')),
    "playlist_index" INTEGER NOT NULL,
    "entry_url" TEXT NOT NULL CHECK ("entry_url" IS NULL OR (length("entry_url") <= 4096)),
    "entry_title" TEXT CHECK ("entry_title" IS NULL OR (length("entry_title") <= 2048)),
    CONSTRAINT "jobs_fk_playlist_items_job_id" FOREIGN KEY ("job_id") REFERENCES "jobs_download_jobs" ("job_id") ON UPDATE NO ACTION ON DELETE CASCADE,
    CONSTRAINT "jobs_fk_playlist_items_playlist_id" FOREIGN KEY ("playlist_id") REFERENCES "jobs_playlists" ("playlist_id") ON UPDATE NO ACTION ON DELETE CASCADE
);

CREATE TABLE "jobs_playlist_scan_entries" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "playlist_id" TEXT NOT NULL CHECK ("playlist_id" IS NULL OR (length("playlist_id") = 32 AND "playlist_id" NOT GLOB '*[^0-9a-f]*')),
    "playlist_index" INTEGER NOT NULL,
    "entry_url" TEXT NOT NULL CHECK ("entry_url" IS NULL OR (length("entry_url") <= 4096)),
    "entry_title" TEXT CHECK ("entry_title" IS NULL OR (length("entry_title") <= 2048)),
    CONSTRAINT "jobs_fk_playlist_scan_entries_playlist_id" FOREIGN KEY ("playlist_id") REFERENCES "jobs_playlists" ("playlist_id") ON UPDATE NO ACTION ON DELETE CASCADE
);

CREATE TABLE "jobs_playlist_source_metadata" (
    "playlist_id" TEXT NOT NULL CHECK ("playlist_id" IS NULL OR (length("playlist_id") = 32 AND "playlist_id" NOT GLOB '*[^0-9a-f]*')),
    "provider_playlist_id" TEXT CHECK ("provider_playlist_id" IS NULL OR (length("provider_playlist_id") <= 512)),
    "title" TEXT CHECK ("title" IS NULL OR (length("title") <= 2048)),
    "total_items" INTEGER NOT NULL DEFAULT 0,
    "last_scanned_at" INTEGER,
    CONSTRAINT "jobs_PK_playlist_source_metadata" PRIMARY KEY ("playlist_id"),
    CONSTRAINT "jobs_fk_playlist_source_metadata_playlist_id" FOREIGN KEY ("playlist_id") REFERENCES "jobs_playlists" ("playlist_id") ON UPDATE NO ACTION ON DELETE CASCADE
);

CREATE TABLE "jobs_playlists" (
    "playlist_id" TEXT NOT NULL CHECK ("playlist_id" IS NULL OR (length("playlist_id") = 32 AND "playlist_id" NOT GLOB '*[^0-9a-f]*')),
    "correlation_id" TEXT NOT NULL CHECK ("correlation_id" IS NULL OR (length("correlation_id") = 32 AND "correlation_id" NOT GLOB '*[^0-9a-f]*')),
    "state" TEXT NOT NULL CHECK ("state" IS NULL OR ("state" IN ('pending_metadata', 'metadata_resolved', 'failed'))),
    "source_url" TEXT NOT NULL CHECK ("source_url" IS NULL OR (length("source_url") <= 4096)),
    "requested_by" TEXT CHECK ("requested_by" IS NULL OR (length("requested_by") <= 255)),
    "storage_key" TEXT CHECK ("storage_key" IS NULL OR (length("storage_key") <= 100)),
    "created_at" INTEGER NOT NULL DEFAULT (CAST(strftime('%s', 'now') AS INTEGER) * 1000000 + CAST(substr(strftime('%f', 'now'), 4, 3) AS INTEGER) * 1000),
    "updated_at" INTEGER NOT NULL DEFAULT (CAST(strftime('%s', 'now') AS INTEGER) * 1000000 + CAST(substr(strftime('%f', 'now'), 4, 3) AS INTEGER) * 1000),
    "completed_at" INTEGER,
    "encode_for_playlist" INTEGER NOT NULL DEFAULT 0 CHECK ("encode_for_playlist" IS NULL OR ("encode_for_playlist" IN (0, 1))),
    "config_set_key" TEXT CHECK ("config_set_key" IS NULL OR (length("config_set_key") <= 100)),
    "cookie_secret_path" TEXT CHECK ("cookie_secret_path" IS NULL OR (length("cookie_secret_path") <= 512)),
    "ytdlp_options_json" TEXT CHECK ("ytdlp_options_json" IS NULL OR (json_valid("ytdlp_options_json"))),
    "priority" INTEGER NOT NULL DEFAULT 0,
    "fetch_comments" INTEGER NOT NULL DEFAULT 0 CHECK ("fetch_comments" IS NULL OR ("fetch_comments" IN (0, 1))),
    "worker_tag" TEXT CHECK ("worker_tag" IS NULL OR (length("worker_tag") <= 50)),
    CONSTRAINT "jobs_PK_playlists" PRIMARY KEY ("playlist_id"),
    CONSTRAINT "jobs_ck_playlists_worker_tag_format" CHECK (worker_tag IS NULL OR (length(worker_tag) BETWEEN 2 AND 50 AND worker_tag NOT GLOB '*[^a-z0-9-]*'))
);

CREATE TABLE "jobs_processed_messages" (
    "message_id" TEXT NOT NULL CHECK ("message_id" IS NULL OR (length("message_id") = 32 AND "message_id" NOT GLOB '*[^0-9a-f]*')),
    "operation_key" TEXT NOT NULL CHECK ("operation_key" IS NULL OR (length("operation_key") <= 512)),
    "job_id" TEXT NOT NULL CHECK ("job_id" IS NULL OR (length("job_id") = 32 AND "job_id" NOT GLOB '*[^0-9a-f]*')),
    "processed_at" INTEGER NOT NULL DEFAULT (CAST(strftime('%s', 'now') AS INTEGER) * 1000000 + CAST(substr(strftime('%f', 'now'), 4, 3) AS INTEGER) * 1000),
    CONSTRAINT "jobs_PK_processed_messages" PRIMARY KEY ("message_id")
);

CREATE TABLE "media_audio_encoding_status" (
    "media_guid" TEXT NOT NULL CHECK ("media_guid" IS NULL OR (length("media_guid") = 32 AND "media_guid" NOT GLOB '*[^0-9a-f]*')),
    "account_id" INTEGER NOT NULL,
    "is_encoded" INTEGER NOT NULL DEFAULT 0 CHECK ("is_encoded" IS NULL OR ("is_encoded" IN (0, 1))),
    "storage_key" TEXT CHECK ("storage_key" IS NULL OR (length("storage_key") <= 100)),
    "storage_path" TEXT CHECK ("storage_path" IS NULL OR (length("storage_path") <= 2048)),
    "encoded_at" INTEGER,
    "updated_at" INTEGER NOT NULL DEFAULT (CAST(strftime('%s', 'now') AS INTEGER) * 1000000 + CAST(substr(strftime('%f', 'now'), 4, 3) AS INTEGER) * 1000),
    CONSTRAINT "media_PK_audio_encoding_status" PRIMARY KEY ("media_guid"),
    CONSTRAINT "media_fk_audio_encoding_status_account_id" FOREIGN KEY ("account_id") REFERENCES "metadata_accounts" ("id") ON UPDATE NO ACTION ON DELETE CASCADE,
    CONSTRAINT "media_fk_audio_encoding_status_media_guid" FOREIGN KEY ("media_guid") REFERENCES "media_media" ("media_guid") ON UPDATE NO ACTION ON DELETE CASCADE
);

CREATE TABLE "media_audio_renditions" (
    "rendition_id" TEXT NOT NULL CHECK ("rendition_id" IS NULL OR (length("rendition_id") = 32 AND "rendition_id" NOT GLOB '*[^0-9a-f]*')),
    "media_guid" TEXT NOT NULL CHECK ("media_guid" IS NULL OR (length("media_guid") = 32 AND "media_guid" NOT GLOB '*[^0-9a-f]*')),
    "source_version_num" INTEGER NOT NULL,
    "status" TEXT NOT NULL CHECK ("status" IS NULL OR ("status" IN ('pending', 'processing', 'ready', 'failed'))),
    "storage_key" TEXT NOT NULL CHECK ("storage_key" IS NULL OR (length("storage_key") <= 100)),
    "storage_path" TEXT CHECK ("storage_path" IS NULL OR (length("storage_path") <= 2048)),
    "content_hash_xxh128" TEXT CHECK ("content_hash_xxh128" IS NULL OR (length("content_hash_xxh128") <= 64)),
    "size_bytes" INTEGER,
    "duration_seconds" INTEGER,
    "error_message" TEXT CHECK ("error_message" IS NULL OR (length("error_message") <= 4096)),
    "created_at" INTEGER NOT NULL DEFAULT (CAST(strftime('%s', 'now') AS INTEGER) * 1000000 + CAST(substr(strftime('%f', 'now'), 4, 3) AS INTEGER) * 1000),
    "updated_at" INTEGER NOT NULL DEFAULT (CAST(strftime('%s', 'now') AS INTEGER) * 1000000 + CAST(substr(strftime('%f', 'now'), 4, 3) AS INTEGER) * 1000),
    CONSTRAINT "media_PK_audio_renditions" PRIMARY KEY ("rendition_id"),
    CONSTRAINT "media_fk_audio_renditions_source_version" FOREIGN KEY ("media_guid", "source_version_num") REFERENCES "media_media_content_id_versions" ("media_guid", "version_num") ON UPDATE NO ACTION ON DELETE CASCADE
);

CREATE TABLE "media_media" (
    "media_guid" TEXT NOT NULL CHECK ("media_guid" IS NULL OR (length("media_guid") = 32 AND "media_guid" NOT GLOB '*[^0-9a-f]*')),
    "created_at" INTEGER NOT NULL DEFAULT (CAST(strftime('%s', 'now') AS INTEGER) * 1000000 + CAST(substr(strftime('%f', 'now'), 4, 3) AS INTEGER) * 1000),
    CONSTRAINT "media_PK_media" PRIMARY KEY ("media_guid")
);

CREATE TABLE "media_media_content_id_versions" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "media_guid" TEXT NOT NULL CHECK ("media_guid" IS NULL OR (length("media_guid") = 32 AND "media_guid" NOT GLOB '*[^0-9a-f]*')),
    "content_hash_xxh128" TEXT NOT NULL CHECK ("content_hash_xxh128" IS NULL OR (length("content_hash_xxh128") <= 64)),
    "storage_key" TEXT NOT NULL CHECK ("storage_key" IS NULL OR (length("storage_key") <= 100)),
    "storage_path" TEXT NOT NULL CHECK ("storage_path" IS NULL OR (length("storage_path") <= 2048)),
    "version_num" INTEGER NOT NULL,
    "ingest_origin" TEXT NOT NULL DEFAULT 'download' CHECK ("ingest_origin" IS NULL OR ("ingest_origin" IN ('download', 'local_import'))),
    CONSTRAINT "media_fk_media_content_id_versions_media_guid" FOREIGN KEY ("media_guid") REFERENCES "media_media" ("media_guid") ON UPDATE NO ACTION ON DELETE CASCADE
);

CREATE TABLE "media_media_source_versions" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "provider" TEXT CHECK ("provider" IS NULL OR (length("provider") <= 255)),
    "source_media_id" TEXT CHECK ("source_media_id" IS NULL OR (length("source_media_id") <= 512)),
    "source_last_modified" INTEGER,
    "media_guid" TEXT NOT NULL CHECK ("media_guid" IS NULL OR (length("media_guid") = 32 AND "media_guid" NOT GLOB '*[^0-9a-f]*')),
    "latest_job_id" TEXT CHECK ("latest_job_id" IS NULL OR (length("latest_job_id") = 32 AND "latest_job_id" NOT GLOB '*[^0-9a-f]*')),
    CONSTRAINT "media_fk_media_source_versions_latest_job_id" FOREIGN KEY ("latest_job_id") REFERENCES "jobs_download_jobs" ("job_id") ON UPDATE NO ACTION ON DELETE SET NULL,
    CONSTRAINT "media_fk_media_source_versions_media_guid" FOREIGN KEY ("media_guid") REFERENCES "media_media" ("media_guid") ON UPDATE NO ACTION ON DELETE CASCADE
);

CREATE TABLE "media_stream_renditions" (
    "rendition_id" TEXT NOT NULL CHECK ("rendition_id" IS NULL OR (length("rendition_id") = 32 AND "rendition_id" NOT GLOB '*[^0-9a-f]*')),
    "media_guid" TEXT NOT NULL CHECK ("media_guid" IS NULL OR (length("media_guid") = 32 AND "media_guid" NOT GLOB '*[^0-9a-f]*')),
    "source_version_num" INTEGER NOT NULL,
    "status" TEXT NOT NULL CHECK ("status" IS NULL OR ("status" IN ('pending', 'processing', 'ready', 'failed'))),
    "storage_key" TEXT NOT NULL CHECK ("storage_key" IS NULL OR (length("storage_key") <= 100)),
    "storage_path" TEXT CHECK ("storage_path" IS NULL OR (length("storage_path") <= 2048)),
    "size_bytes" INTEGER,
    "duration_seconds" INTEGER,
    "error_message" TEXT CHECK ("error_message" IS NULL OR (length("error_message") <= 4096)),
    "created_at" INTEGER NOT NULL DEFAULT (CAST(strftime('%s', 'now') AS INTEGER) * 1000000 + CAST(substr(strftime('%f', 'now'), 4, 3) AS INTEGER) * 1000),
    "updated_at" INTEGER NOT NULL DEFAULT (CAST(strftime('%s', 'now') AS INTEGER) * 1000000 + CAST(substr(strftime('%f', 'now'), 4, 3) AS INTEGER) * 1000),
    CONSTRAINT "media_PK_stream_renditions" PRIMARY KEY ("rendition_id"),
    CONSTRAINT "media_fk_stream_renditions_source_version" FOREIGN KEY ("media_guid", "source_version_num") REFERENCES "media_media_content_id_versions" ("media_guid", "version_num") ON UPDATE NO ACTION ON DELETE CASCADE
);

CREATE TABLE "media_user_media_likes" (
    "owner_subject" TEXT NOT NULL,
    "media_guid" TEXT NOT NULL CHECK ("media_guid" IS NULL OR (length("media_guid") = 32 AND "media_guid" NOT GLOB '*[^0-9a-f]*')),
    "liked_at" INTEGER NOT NULL,
    "updated_at" INTEGER NOT NULL,
    CONSTRAINT "media_pk_user_media_likes" PRIMARY KEY ("owner_subject", "media_guid"),
    CONSTRAINT "media_fk_user_media_likes_media_guid" FOREIGN KEY ("media_guid") REFERENCES "media_media" ("media_guid") ON UPDATE NO ACTION ON DELETE CASCADE
);

CREATE TABLE "media_watch_states" (
    "owner_subject" TEXT NOT NULL,
    "media_guid" TEXT NOT NULL CHECK ("media_guid" IS NULL OR (length("media_guid") = 32 AND "media_guid" NOT GLOB '*[^0-9a-f]*')),
    "position_seconds" REAL,
    "duration_seconds" REAL,
    "completed" INTEGER NOT NULL DEFAULT 0 CHECK ("completed" IS NULL OR ("completed" IN (0, 1))),
    "watched_at" INTEGER,
    "last_played_at" INTEGER NOT NULL,
    "created_at" INTEGER NOT NULL DEFAULT (CAST(strftime('%s', 'now') AS INTEGER) * 1000000 + CAST(substr(strftime('%f', 'now'), 4, 3) AS INTEGER) * 1000),
    "updated_at" INTEGER NOT NULL DEFAULT (CAST(strftime('%s', 'now') AS INTEGER) * 1000000 + CAST(substr(strftime('%f', 'now'), 4, 3) AS INTEGER) * 1000),
    CONSTRAINT "media_pk_watch_states" PRIMARY KEY ("owner_subject", "media_guid"),
    CONSTRAINT "media_ck_watch_states_duration_positive" CHECK (((duration_seconds IS NULL) OR (duration_seconds > (0)))),
    CONSTRAINT "media_ck_watch_states_position_nonnegative" CHECK (((position_seconds IS NULL) OR (position_seconds >= (0)))),
    CONSTRAINT "media_fk_watch_states_media_guid" FOREIGN KEY ("media_guid") REFERENCES "media_media" ("media_guid") ON UPDATE NO ACTION ON DELETE CASCADE
);

CREATE TABLE "metadata_account_external_ids" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "account_id" INTEGER NOT NULL,
    "platform" TEXT NOT NULL CHECK ("platform" IS NULL OR (length("platform") <= 50)),
    "id_kind" TEXT NOT NULL CHECK ("id_kind" IS NULL OR (length("id_kind") <= 50)),
    "external_id" TEXT NOT NULL,
    CONSTRAINT "metadata_fk_account_external_ids_account_id" FOREIGN KEY ("account_id") REFERENCES "metadata_accounts" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
);

CREATE TABLE "metadata_accounts" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "platform" TEXT NOT NULL CHECK ("platform" IS NULL OR (length("platform") <= 50)),
    "account_name" TEXT NOT NULL,
    "account_handle" TEXT NOT NULL,
    "account_url" TEXT,
    "account_creation_date" INTEGER,
    "account_follower_count" INTEGER,
    "is_verified" INTEGER NOT NULL DEFAULT 0 CHECK ("is_verified" IS NULL OR ("is_verified" IN (0, 1))),
    "account_description" TEXT,
    "avatar_storage_path" TEXT,
    "banner_storage_path" TEXT,
    "storage_key" TEXT CHECK ("storage_key" IS NULL OR (length("storage_key") <= 255))
);

CREATE TABLE "metadata_artists" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "artist_name" TEXT NOT NULL
);

CREATE TABLE "metadata_audio_stream_details" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "media_stream_id" INTEGER NOT NULL,
    "channels" INTEGER NOT NULL DEFAULT 0,
    "channel_layout" TEXT NOT NULL,
    "sample_rate_hz" INTEGER NOT NULL DEFAULT 0,
    "profile" TEXT NOT NULL,
    CONSTRAINT "metadata_fk_audio_stream_details_media_stream_id" FOREIGN KEY ("media_stream_id") REFERENCES "metadata_media_streams" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
);

CREATE TABLE "metadata_cast_members" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "cast_name" TEXT NOT NULL
);

CREATE TABLE "metadata_categories" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "category_name" TEXT NOT NULL
);

CREATE TABLE "metadata_chapter_data" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "media_base_id" INTEGER NOT NULL,
    "title" TEXT NOT NULL,
    "start_ticks" INTEGER NOT NULL DEFAULT 0,
    "end_ticks" INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT "metadata_fk_chapter_data_media_base_id" FOREIGN KEY ("media_base_id") REFERENCES "metadata_media_base" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
);

CREATE TABLE "metadata_genres" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "genre_name" TEXT NOT NULL
);

CREATE TABLE "metadata_media_artists" (
    "media_metadata_id" INTEGER NOT NULL,
    "artist_id" INTEGER NOT NULL,
    "is_album_artist" INTEGER NOT NULL DEFAULT 0 CHECK ("is_album_artist" IS NULL OR ("is_album_artist" IN (0, 1))),
    CONSTRAINT "metadata_pk_media_artists" PRIMARY KEY ("media_metadata_id", "artist_id"),
    CONSTRAINT "metadata_fk_media_artists_artist_id" FOREIGN KEY ("artist_id") REFERENCES "metadata_artists" ("id") ON UPDATE NO ACTION ON DELETE CASCADE,
    CONSTRAINT "metadata_fk_media_artists_media_metadata_id" FOREIGN KEY ("media_metadata_id") REFERENCES "metadata_media_metadata" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
);

CREATE TABLE "metadata_media_base" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "media_guid" TEXT NOT NULL CHECK ("media_guid" IS NULL OR (length("media_guid") = 32 AND "media_guid" NOT GLOB '*[^0-9a-f]*')),
    "duration_ticks" INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT "metadata_fk_metadata_media_base_media_guid" FOREIGN KEY ("media_guid") REFERENCES "media_media" ("media_guid") ON UPDATE NO ACTION ON DELETE CASCADE
);

CREATE TABLE "metadata_media_captions" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "media_guid" TEXT NOT NULL CHECK ("media_guid" IS NULL OR (length("media_guid") = 32 AND "media_guid" NOT GLOB '*[^0-9a-f]*')),
    "storage_path" TEXT NOT NULL,
    "caption_type" TEXT NOT NULL CHECK ("caption_type" IS NULL OR ("caption_type" IN ('subtitles', 'automatic_captions'))),
    "two_digit_language_code" TEXT NOT NULL CHECK ("two_digit_language_code" IS NULL OR (length("two_digit_language_code") <= 10)),
    "name" TEXT,
    "storage_key" TEXT CHECK ("storage_key" IS NULL OR (length("storage_key") <= 255)),
    CONSTRAINT "metadata_fk_metadata_media_captions_media_guid" FOREIGN KEY ("media_guid") REFERENCES "media_media" ("media_guid") ON UPDATE NO ACTION ON DELETE CASCADE
);

CREATE TABLE "metadata_media_cast" (
    "media_metadata_id" INTEGER NOT NULL,
    "cast_member_id" INTEGER NOT NULL,
    CONSTRAINT "metadata_pk_media_cast" PRIMARY KEY ("media_metadata_id", "cast_member_id"),
    CONSTRAINT "metadata_fk_media_cast_cast_member_id" FOREIGN KEY ("cast_member_id") REFERENCES "metadata_cast_members" ("id") ON UPDATE NO ACTION ON DELETE CASCADE,
    CONSTRAINT "metadata_fk_media_cast_media_metadata_id" FOREIGN KEY ("media_metadata_id") REFERENCES "metadata_media_metadata" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
);

CREATE TABLE "metadata_media_categories" (
    "media_metadata_id" INTEGER NOT NULL,
    "category_id" INTEGER NOT NULL,
    CONSTRAINT "metadata_pk_media_categories" PRIMARY KEY ("media_metadata_id", "category_id"),
    CONSTRAINT "metadata_fk_media_categories_category_id" FOREIGN KEY ("category_id") REFERENCES "metadata_categories" ("id") ON UPDATE NO ACTION ON DELETE CASCADE,
    CONSTRAINT "metadata_fk_media_categories_media_metadata_id" FOREIGN KEY ("media_metadata_id") REFERENCES "metadata_media_metadata" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
);

CREATE TABLE "metadata_media_comments" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "media_guid" TEXT NOT NULL CHECK ("media_guid" IS NULL OR (length("media_guid") = 32 AND "media_guid" NOT GLOB '*[^0-9a-f]*')),
    "comment_id" TEXT NOT NULL,
    "parent_comment_id" TEXT,
    "text_comment" TEXT NOT NULL,
    "account_id" INTEGER NOT NULL,
    "comment_timestamp" INTEGER NOT NULL,
    "like_count" INTEGER,
    "dislike_count" INTEGER,
    "is_favorited" INTEGER NOT NULL DEFAULT 0 CHECK ("is_favorited" IS NULL OR ("is_favorited" IN (0, 1))),
    "is_uploader" INTEGER NOT NULL DEFAULT 0 CHECK ("is_uploader" IS NULL OR ("is_uploader" IN (0, 1))),
    "is_pinned" INTEGER NOT NULL DEFAULT 0 CHECK ("is_pinned" IS NULL OR ("is_pinned" IN (0, 1))),
    CONSTRAINT "metadata_fk_media_comments_account_id" FOREIGN KEY ("account_id") REFERENCES "metadata_accounts" ("id") ON UPDATE NO ACTION ON DELETE CASCADE,
    CONSTRAINT "metadata_fk_metadata_media_comments_media_guid" FOREIGN KEY ("media_guid") REFERENCES "media_media" ("media_guid") ON UPDATE NO ACTION ON DELETE CASCADE
);

CREATE TABLE "metadata_media_format_details" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "media_base_id" INTEGER NOT NULL,
    "duration_ticks" INTEGER NOT NULL DEFAULT 0,
    "start_time_ticks" INTEGER NOT NULL DEFAULT 0,
    "format_long_names" TEXT NOT NULL,
    "stream_count" INTEGER NOT NULL DEFAULT 0,
    "bit_rate" REAL NOT NULL DEFAULT 0,
    CONSTRAINT "metadata_fk_media_format_details_media_base_id" FOREIGN KEY ("media_base_id") REFERENCES "metadata_media_base" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
);

CREATE TABLE "metadata_media_genres" (
    "media_metadata_id" INTEGER NOT NULL,
    "genre_id" INTEGER NOT NULL,
    CONSTRAINT "metadata_pk_media_genres" PRIMARY KEY ("media_metadata_id", "genre_id"),
    CONSTRAINT "metadata_fk_media_genres_genre_id" FOREIGN KEY ("genre_id") REFERENCES "metadata_genres" ("id") ON UPDATE NO ACTION ON DELETE CASCADE,
    CONSTRAINT "metadata_fk_media_genres_media_metadata_id" FOREIGN KEY ("media_metadata_id") REFERENCES "metadata_media_metadata" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
);

CREATE TABLE "metadata_media_live_chat" (
    "media_guid" TEXT NOT NULL CHECK ("media_guid" IS NULL OR (length("media_guid") = 32 AND "media_guid" NOT GLOB '*[^0-9a-f]*')),
    "version_num" INTEGER,
    "message_count" INTEGER NOT NULL DEFAULT 0,
    "first_offset_ms" INTEGER NOT NULL DEFAULT 0,
    "last_offset_ms" INTEGER NOT NULL DEFAULT 0,
    "ingested_at" INTEGER NOT NULL DEFAULT (CAST(strftime('%s', 'now') AS INTEGER) * 1000000 + CAST(substr(strftime('%f', 'now'), 4, 3) AS INTEGER) * 1000),
    CONSTRAINT "metadata_PK_media_live_chat" PRIMARY KEY ("media_guid")
);

CREATE TABLE "metadata_media_metadata" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "media_guid" TEXT NOT NULL CHECK ("media_guid" IS NULL OR (length("media_guid") = 32 AND "media_guid" NOT GLOB '*[^0-9a-f]*')),
    "account_id" INTEGER NOT NULL,
    "external_media_id" TEXT,
    "metadata_scrape_date" INTEGER NOT NULL,
    "thumbnail_storage_path" TEXT,
    "age_limit" INTEGER,
    "average_rating" REAL,
    "like_count" INTEGER,
    "dislike_count" INTEGER,
    "duration" REAL,
    "description" TEXT,
    "release_date" INTEGER,
    "title" TEXT,
    "was_live" INTEGER NOT NULL DEFAULT 0 CHECK ("was_live" IS NULL OR ("was_live" IN (0, 1))),
    "webpage_url" TEXT,
    "view_count" INTEGER,
    "comment_count" INTEGER,
    "availability" TEXT CHECK ("availability" IS NULL OR ("availability" IN ('unknown', 'private', 'premium_only', 'subscriber_only', 'needs_auth', 'unlisted', 'public'))),
    "location" TEXT,
    "storage_key" TEXT CHECK ("storage_key" IS NULL OR (length("storage_key") <= 255)),
    CONSTRAINT "metadata_fk_media_metadata_account_id" FOREIGN KEY ("account_id") REFERENCES "metadata_accounts" ("id") ON UPDATE NO ACTION ON DELETE CASCADE,
    CONSTRAINT "metadata_fk_metadata_media_metadata_media_guid" FOREIGN KEY ("media_guid") REFERENCES "media_media" ("media_guid") ON UPDATE NO ACTION ON DELETE CASCADE
);

CREATE TABLE "metadata_media_streams" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "media_base_id" INTEGER NOT NULL,
    "stream_type" TEXT NOT NULL CHECK ("stream_type" IS NULL OR (length("stream_type") <= 20)),
    "is_primary" INTEGER NOT NULL DEFAULT 0 CHECK ("is_primary" IS NULL OR ("is_primary" IN (0, 1))),
    "codec_name" TEXT NOT NULL,
    "codec_long_name" TEXT NOT NULL,
    "bit_rate" INTEGER NOT NULL DEFAULT 0,
    "bit_depth" INTEGER,
    "start_time_ticks" INTEGER NOT NULL DEFAULT 0,
    "duration_ticks" INTEGER NOT NULL DEFAULT 0,
    "language" TEXT CHECK ("language" IS NULL OR (length("language") <= 50)),
    CONSTRAINT "metadata_fk_media_streams_media_base_id" FOREIGN KEY ("media_base_id") REFERENCES "metadata_media_base" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
);

CREATE TABLE "metadata_media_tags" (
    "media_metadata_id" INTEGER NOT NULL,
    "tag_id" INTEGER NOT NULL,
    CONSTRAINT "metadata_pk_media_tags" PRIMARY KEY ("media_metadata_id", "tag_id"),
    CONSTRAINT "metadata_fk_media_tags_media_metadata_id" FOREIGN KEY ("media_metadata_id") REFERENCES "metadata_media_metadata" ("id") ON UPDATE NO ACTION ON DELETE CASCADE,
    CONSTRAINT "metadata_fk_media_tags_tag_id" FOREIGN KEY ("tag_id") REFERENCES "metadata_tags" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
);

CREATE TABLE "metadata_music_metadata" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "media_guid" TEXT NOT NULL CHECK ("media_guid" IS NULL OR (length("media_guid") = 32 AND "media_guid" NOT GLOB '*[^0-9a-f]*')),
    "album_title" TEXT NOT NULL,
    "album_type" TEXT,
    "disc_number" INTEGER,
    "release_year" INTEGER,
    "track_title" TEXT NOT NULL,
    "track_number" INTEGER NOT NULL,
    "composer" TEXT,
    CONSTRAINT "metadata_fk_metadata_music_metadata_media_guid" FOREIGN KEY ("media_guid") REFERENCES "media_media" ("media_guid") ON UPDATE NO ACTION ON DELETE CASCADE
);

CREATE TABLE "metadata_series_metadata" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "media_guid" TEXT NOT NULL CHECK ("media_guid" IS NULL OR (length("media_guid") = 32 AND "media_guid" NOT GLOB '*[^0-9a-f]*')),
    "series_name" TEXT NOT NULL,
    "season_count" INTEGER,
    "season_number" INTEGER NOT NULL,
    "season_name" TEXT,
    "episode_number" INTEGER NOT NULL,
    "episode_name" TEXT NOT NULL,
    CONSTRAINT "metadata_fk_metadata_series_metadata_media_guid" FOREIGN KEY ("media_guid") REFERENCES "media_media" ("media_guid") ON UPDATE NO ACTION ON DELETE CASCADE
);

CREATE TABLE "metadata_tags" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "tag_name" TEXT NOT NULL
);

CREATE TABLE "metadata_video_stream_details" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "media_stream_id" INTEGER NOT NULL,
    "avg_frame_rate" REAL NOT NULL DEFAULT 0,
    "bits_per_raw_sample" INTEGER NOT NULL DEFAULT 0,
    "display_aspect_ratio_width" INTEGER NOT NULL DEFAULT 0,
    "display_aspect_ratio_height" INTEGER NOT NULL DEFAULT 0,
    "profile" TEXT NOT NULL,
    "width" INTEGER NOT NULL DEFAULT 0,
    "height" INTEGER NOT NULL DEFAULT 0,
    "pixel_format" TEXT NOT NULL,
    "rotation" INTEGER NOT NULL DEFAULT 0,
    "color_space" TEXT NOT NULL,
    "color_transfer" TEXT NOT NULL,
    "color_primaries" TEXT NOT NULL,
    "hdr_type" TEXT NOT NULL DEFAULT 'SDR' CHECK ("hdr_type" IS NULL OR (length("hdr_type") <= 20)),
    CONSTRAINT "metadata_fk_video_stream_details_media_stream_id" FOREIGN KEY ("media_stream_id") REFERENCES "metadata_media_streams" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
);

CREATE TABLE "notes_user_notes" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "owner_subject" TEXT NOT NULL CHECK ("owner_subject" IS NULL OR (length("owner_subject") <= 255)),
    "target_type" TEXT NOT NULL CHECK ("target_type" IS NULL OR (length("target_type") <= 32)),
    "target_id" TEXT NOT NULL CHECK ("target_id" IS NULL OR (length("target_id") <= 64)),
    "note" TEXT NOT NULL CHECK ("note" IS NULL OR (length("note") <= 8192)),
    "created_at" INTEGER NOT NULL DEFAULT (CAST(strftime('%s', 'now') AS INTEGER) * 1000000 + CAST(substr(strftime('%f', 'now'), 4, 3) AS INTEGER) * 1000),
    "updated_at" INTEGER NOT NULL DEFAULT (CAST(strftime('%s', 'now') AS INTEGER) * 1000000 + CAST(substr(strftime('%f', 'now'), 4, 3) AS INTEGER) * 1000)
);

CREATE TABLE "playlists_media_playlist_membership" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "media_guid" TEXT NOT NULL CHECK ("media_guid" IS NULL OR (length("media_guid") = 32 AND "media_guid" NOT GLOB '*[^0-9a-f]*')),
    "playlist_id" TEXT NOT NULL CHECK ("playlist_id" IS NULL OR (length("playlist_id") = 32 AND "playlist_id" NOT GLOB '*[^0-9a-f]*')),
    "playlist_index" INTEGER NOT NULL,
    CONSTRAINT "playlists_fk_media_playlist_membership_media_guid" FOREIGN KEY ("media_guid") REFERENCES "media_media" ("media_guid") ON UPDATE NO ACTION ON DELETE CASCADE
);

CREATE TABLE "playlists_playlist_metadata" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "playlist_id" TEXT NOT NULL CHECK ("playlist_id" IS NULL OR (length("playlist_id") = 32 AND "playlist_id" NOT GLOB '*[^0-9a-f]*')),
    "title" TEXT
);

CREATE TABLE "playlists_user_playlist_items" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "playlist_id" TEXT NOT NULL CHECK ("playlist_id" IS NULL OR (length("playlist_id") = 32 AND "playlist_id" NOT GLOB '*[^0-9a-f]*')),
    "media_guid" TEXT NOT NULL CHECK ("media_guid" IS NULL OR (length("media_guid") = 32 AND "media_guid" NOT GLOB '*[^0-9a-f]*')),
    "position" INTEGER NOT NULL,
    "added_at" INTEGER NOT NULL DEFAULT (CAST(strftime('%s', 'now') AS INTEGER) * 1000000 + CAST(substr(strftime('%f', 'now'), 4, 3) AS INTEGER) * 1000),
    CONSTRAINT "playlists_fk_user_playlist_items_media_guid" FOREIGN KEY ("media_guid") REFERENCES "media_media" ("media_guid") ON UPDATE NO ACTION ON DELETE CASCADE,
    CONSTRAINT "playlists_fk_user_playlist_items_playlist_id" FOREIGN KEY ("playlist_id") REFERENCES "playlists_user_playlists" ("playlist_id") ON UPDATE NO ACTION ON DELETE CASCADE
);

CREATE TABLE "playlists_user_playlists" (
    "playlist_id" TEXT NOT NULL CHECK ("playlist_id" IS NULL OR (length("playlist_id") = 32 AND "playlist_id" NOT GLOB '*[^0-9a-f]*')),
    "owner_subject" TEXT NOT NULL CHECK ("owner_subject" IS NULL OR (length("owner_subject") <= 255)),
    "name" TEXT NOT NULL CHECK ("name" IS NULL OR (length("name") <= 255)),
    "description" TEXT CHECK ("description" IS NULL OR (length("description") <= 2048)),
    "created_at" INTEGER NOT NULL DEFAULT (CAST(strftime('%s', 'now') AS INTEGER) * 1000000 + CAST(substr(strftime('%f', 'now'), 4, 3) AS INTEGER) * 1000),
    "updated_at" INTEGER NOT NULL DEFAULT (CAST(strftime('%s', 'now') AS INTEGER) * 1000000 + CAST(substr(strftime('%f', 'now'), 4, 3) AS INTEGER) * 1000),
    CONSTRAINT "playlists_PK_user_playlists" PRIMARY KEY ("playlist_id")
);

CREATE TABLE "scheduling_scheduled_tasks" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "key" TEXT NOT NULL CHECK ("key" IS NULL OR (length("key") <= 100)),
    "task_type" TEXT NOT NULL CHECK ("task_type" IS NULL OR (length("task_type") <= 100)),
    "cron" TEXT CHECK ("cron" IS NULL OR (length("cron") <= 255)),
    "interval_seconds" INTEGER,
    "timezone" TEXT NOT NULL DEFAULT 'UTC' CHECK ("timezone" IS NULL OR (length("timezone") <= 100)),
    "enabled" INTEGER NOT NULL DEFAULT 0 CHECK ("enabled" IS NULL OR ("enabled" IN (0, 1))),
    "catchup_policy" TEXT NOT NULL DEFAULT 'Coalesce' CHECK ("catchup_policy" IS NULL OR (length("catchup_policy") <= 32)),
    "last_attempt_at" INTEGER,
    "last_success_at" INTEGER,
    "next_due_at" INTEGER,
    "created_at" INTEGER NOT NULL DEFAULT (CAST(strftime('%s', 'now') AS INTEGER) * 1000000 + CAST(substr(strftime('%f', 'now'), 4, 3) AS INTEGER) * 1000),
    "last_updated" INTEGER,
    "last_run_status" TEXT CHECK ("last_run_status" IS NULL OR (length("last_run_status") <= 32)),
    "retention_days" INTEGER NOT NULL DEFAULT 0,
    "include_failed" INTEGER NOT NULL DEFAULT 0 CHECK ("include_failed" IS NULL OR ("include_failed" IN (0, 1))),
    CONSTRAINT "scheduling_ck_scheduled_tasks_interval_positive" CHECK (((interval_seconds IS NULL) OR (interval_seconds > 0))),
    CONSTRAINT "scheduling_ck_scheduled_tasks_key_format" CHECK (length("key") BETWEEN 2 AND 100 AND "key" NOT GLOB '*[^a-z0-9-]*'),
    CONSTRAINT "scheduling_ck_scheduled_tasks_retention_days_nonnegative" CHECK ((retention_days >= 0)),
    CONSTRAINT "scheduling_ck_scheduled_tasks_trigger_xor" CHECK ((((cron IS NOT NULL) AND (interval_seconds IS NULL)) OR ((cron IS NULL) AND (interval_seconds IS NOT NULL))))
);

CREATE TABLE "statistics_account_daily_states" (
    "day" TEXT NOT NULL,
    "account_id" INTEGER NOT NULL,
    "state" TEXT NOT NULL CHECK ("state" IS NULL OR (length("state") <= 32)),
    "job_count" INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT "statistics_pk_account_daily_states" PRIMARY KEY ("day", "account_id", "state"),
    CONSTRAINT "statistics_fk_account_daily_states_account_id" FOREIGN KEY ("account_id") REFERENCES "metadata_accounts" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
);

CREATE TABLE "statistics_channel_media_downloads" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "media_guid" TEXT NOT NULL CHECK ("media_guid" IS NULL OR (length("media_guid") = 32 AND "media_guid" NOT GLOB '*[^0-9a-f]*')),
    "account_id" INTEGER NOT NULL,
    "platform" TEXT NOT NULL CHECK ("platform" IS NULL OR (length("platform") <= 50)),
    "bytes" INTEGER NOT NULL DEFAULT 0,
    "duration_seconds" REAL NOT NULL DEFAULT 0,
    "completed_at" INTEGER NOT NULL,
    CONSTRAINT "statistics_fk_channel_media_downloads_account_id" FOREIGN KEY ("account_id") REFERENCES "metadata_accounts" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
);

CREATE TABLE "statistics_creator_source_daily_states" (
    "day" TEXT NOT NULL,
    "creator_source_id" INTEGER NOT NULL,
    "state" TEXT NOT NULL CHECK ("state" IS NULL OR (length("state") <= 32)),
    "job_count" INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT "statistics_pk_creator_source_daily_states" PRIMARY KEY ("day", "creator_source_id", "state"),
    CONSTRAINT "statistics_fk_creator_source_daily_states_creator_source_id" FOREIGN KEY ("creator_source_id") REFERENCES "discovery_creator_sources" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
);

CREATE TABLE "statistics_download_daily_activity" (
    "day" TEXT NOT NULL,
    "state" TEXT NOT NULL CHECK ("state" IS NULL OR (length("state") <= 32)),
    "job_count" INTEGER NOT NULL DEFAULT 0,
    "bytes" INTEGER NOT NULL DEFAULT 0,
    "duration_seconds" REAL NOT NULL DEFAULT 0,
    CONSTRAINT "statistics_pk_download_daily_activity" PRIMARY KEY ("day", "state")
);

CREATE TABLE "storage_storage_keys" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "key" TEXT NOT NULL CHECK ("key" IS NULL OR (length("key") <= 100)),
    "method" TEXT NOT NULL CHECK ("method" IS NULL OR (length("method") <= 50)),
    "description" TEXT CHECK ("description" IS NULL OR (length("description") <= 500)),
    "created_at" INTEGER NOT NULL DEFAULT (CAST(strftime('%s', 'now') AS INTEGER) * 1000000 + CAST(substr(strftime('%f', 'now'), 4, 3) AS INTEGER) * 1000),
    "last_updated" INTEGER,
    "worker_tag" TEXT CHECK ("worker_tag" IS NULL OR (length("worker_tag") <= 50)),
    CONSTRAINT "storage_ck_storage_keys_key_format" CHECK (length("key") BETWEEN 2 AND 100 AND "key" NOT GLOB '*[^a-z0-9-]*')
);

CREATE TABLE "storage_storage_keys_local" (
    "storage_key_id" INTEGER NOT NULL,
    "protocol" TEXT NOT NULL CHECK ("protocol" IS NULL OR ("protocol" IN ('local'))),
    "path" TEXT NOT NULL CHECK ("path" IS NULL OR (length("path") <= 2048)),
    CONSTRAINT "storage_PK_storage_keys_local" PRIMARY KEY ("storage_key_id"),
    CONSTRAINT "storage_fk_storage_keys_local_storage_key_id" FOREIGN KEY ("storage_key_id") REFERENCES "storage_storage_keys" ("id") ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE "storage_storage_keys_network" (
    "storage_key_id" INTEGER NOT NULL,
    "protocol" TEXT NOT NULL CHECK ("protocol" IS NULL OR ("protocol" IN ('ftp', 'ftps', 'sftp', 'nfs', 'smb', 'cifs'))),
    "host" TEXT NOT NULL CHECK ("host" IS NULL OR (length("host") <= 255)),
    "port" INTEGER,
    "username" TEXT CHECK ("username" IS NULL OR (length("username") <= 255)),
    "base_path" TEXT CHECK ("base_path" IS NULL OR (length("base_path") <= 2048)),
    "mount_path" TEXT CHECK ("mount_path" IS NULL OR (length("mount_path") <= 2048)),
    "share_name" TEXT CHECK ("share_name" IS NULL OR (length("share_name") <= 255)),
    "domain" TEXT CHECK ("domain" IS NULL OR (length("domain") <= 255)),
    "export_path" TEXT CHECK ("export_path" IS NULL OR (length("export_path") <= 2048)),
    "nfs_user_id" INTEGER,
    "nfs_group_id" INTEGER,
    CONSTRAINT "storage_PK_storage_keys_network" PRIMARY KEY ("storage_key_id"),
    CONSTRAINT "storage_fk_storage_keys_network_storage_key_id" FOREIGN KEY ("storage_key_id") REFERENCES "storage_storage_keys" ("id") ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE "storage_storage_keys_object_azure_blob" (
    "storage_key_id" INTEGER NOT NULL,
    "credential_mode" TEXT NOT NULL CHECK ("credential_mode" IS NULL OR ("credential_mode" IN ('account_key', 'connection_string', 'sas_url'))),
    "container_name" TEXT CHECK ("container_name" IS NULL OR (length("container_name") <= 255)),
    "azure_account_name" TEXT CHECK ("azure_account_name" IS NULL OR (length("azure_account_name") <= 255)),
    CONSTRAINT "storage_PK_storage_keys_object_azure_blob" PRIMARY KEY ("storage_key_id"),
    CONSTRAINT "storage_fk_storage_keys_object_azure_blob_storage_key_id" FOREIGN KEY ("storage_key_id") REFERENCES "storage_storage_keys" ("id") ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE "storage_storage_keys_object_google_cloud_storage" (
    "storage_key_id" INTEGER NOT NULL,
    "bucket_name" TEXT NOT NULL CHECK ("bucket_name" IS NULL OR (length("bucket_name") <= 255)),
    "credential_mode" TEXT NOT NULL CHECK ("credential_mode" IS NULL OR ("credential_mode" IN ('credentials_json', 'credentials_file_path', 'workload_identity', 'default_credentials'))),
    "gcp_credentials_file_path" TEXT CHECK ("gcp_credentials_file_path" IS NULL OR (length("gcp_credentials_file_path") <= 2048)),
    "gcp_project_id" TEXT CHECK ("gcp_project_id" IS NULL OR (length("gcp_project_id") <= 255)),
    CONSTRAINT "storage_PK_storage_keys_object_google_cloud_storage" PRIMARY KEY ("storage_key_id"),
    CONSTRAINT "storage_fk_storage_keys_object_google_cloud_storage_storage_key_id" FOREIGN KEY ("storage_key_id") REFERENCES "storage_storage_keys" ("id") ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE "storage_storage_keys_object_s3_compatible" (
    "storage_key_id" INTEGER NOT NULL,
    "provider" TEXT NOT NULL CHECK ("provider" IS NULL OR ("provider" IN ('aws_s3', 'min_io', 'digital_ocean_spaces'))),
    "bucket_name" TEXT NOT NULL CHECK ("bucket_name" IS NULL OR (length("bucket_name") <= 255)),
    "region" TEXT CHECK ("region" IS NULL OR (length("region") <= 255)),
    "endpoint" TEXT CHECK ("endpoint" IS NULL OR (length("endpoint") <= 2048)),
    "force_path_style" INTEGER NOT NULL DEFAULT 0 CHECK ("force_path_style" IS NULL OR ("force_path_style" IN (0, 1))),
    "use_ssl" INTEGER CHECK ("use_ssl" IS NULL OR ("use_ssl" IN (0, 1))),
    "has_session_token" INTEGER NOT NULL DEFAULT 0 CHECK ("has_session_token" IS NULL OR ("has_session_token" IN (0, 1))),
    CONSTRAINT "storage_PK_storage_keys_object_s3_compatible" PRIMARY KEY ("storage_key_id"),
    CONSTRAINT "storage_fk_storage_keys_object_s3_compatible_storage_key_id" FOREIGN KEY ("storage_key_id") REFERENCES "storage_storage_keys" ("id") ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE UNIQUE INDEX "auth_ux_access_policies_name" ON "auth_access_policies" (lower(name));
CREATE INDEX "auth_ix_access_policy_age_minimum" ON "auth_access_policy_age_tiers" (minimum_age);
CREATE INDEX "auth_ix_access_policy_assignments_principal" ON "auth_access_policy_assignments" (principal_type, principal_id);
CREATE INDEX "auth_ix_access_policy_media_guid" ON "auth_access_policy_media" (media_guid);
CREATE INDEX "auth_ix_access_policy_providers_provider" ON "auth_access_policy_providers" (provider);
CREATE UNIQUE INDEX "auth_ux_cookie_profiles_owner_profile" ON "auth_cookie_profiles" (owner_subject, profile_key);
CREATE UNIQUE INDEX "auth_ux_froststream_users_authentik_subject_id" ON "auth_froststream_users" (authentik_subject_id);
CREATE INDEX "discovery_ix_creator_sources_account_id" ON "discovery_creator_sources" (account_id);
CREATE INDEX "discovery_ix_creator_sources_scan_enabled" ON "discovery_creator_sources" (scan_enabled);
CREATE UNIQUE INDEX "discovery_uq_creator_sources_source_url" ON "discovery_creator_sources" (source_url);
CREATE INDEX "discovery_ix_discovered_media_creator_source_id" ON "discovery_discovered_media" (creator_source_id);
CREATE INDEX "discovery_ix_discovered_media_metadata_status" ON "discovery_discovered_media" (metadata_status);
CREATE INDEX "discovery_ix_discovered_media_platform_discovery_status" ON "discovery_discovered_media" (platform, discovery_status);
CREATE UNIQUE INDEX "discovery_ux_discovered_media_identity" ON "discovery_discovered_media" (platform, extractor, external_media_id);
CREATE UNIQUE INDEX "downloads_uq_download_config_sets_owner_key" ON "downloads_download_config_sets" (owner_subject, key);
CREATE UNIQUE INDEX "downloads_uq_download_option_presets_key" ON "downloads_download_option_presets" (key);
CREATE INDEX "imports_ix_import_session_items_session_item_id" ON "imports_import_session_items" (session_id, item_id);
CREATE INDEX "imports_ix_import_session_items_session_metadata_state" ON "imports_import_session_items" (session_id, metadata_state) WHERE (excluded = 0);
CREATE INDEX "imports_ix_import_session_items_session_status" ON "imports_import_session_items" (session_id, status);
CREATE UNIQUE INDEX "imports_ux_import_session_items_session_relative_path" ON "imports_import_session_items" (session_id, relative_path);
CREATE INDEX "imports_ix_import_sessions_status_updated_at" ON "imports_import_sessions" (status, updated_at);
CREATE INDEX "imports_ix_local_import_batches_status_updated_at" ON "imports_local_import_batches" (status, updated_at);
CREATE INDEX "imports_ix_local_import_items_batch_status" ON "imports_local_import_items" (batch_id, status);
CREATE UNIQUE INDEX "imports_ux_local_import_items_batch_item_index" ON "imports_local_import_items" (batch_id, item_index);
CREATE UNIQUE INDEX "jobs_ux_download_artifacts_run_key" ON "jobs_download_artifacts" (run_id, artifact_key);
CREATE UNIQUE INDEX "jobs_ux_download_groups_correlation_id" ON "jobs_download_groups" (correlation_id);
CREATE INDEX "jobs_ix_download_job_history_job_id_recorded_at" ON "jobs_download_job_history" (job_id, recorded_at);
CREATE INDEX "jobs_ix_download_job_progress_log_job_id_recorded_at" ON "jobs_download_job_progress_log" (job_id, recorded_at);
CREATE UNIQUE INDEX "jobs_ux_download_job_runs_job_run_number" ON "jobs_download_job_runs" (job_id, run_number);
CREATE INDEX "jobs_ix_download_job_warnings_run_stage" ON "jobs_download_job_warnings" (run_id, stage, artifact_key);
CREATE INDEX "jobs_ix_download_jobs_correlation_id" ON "jobs_download_jobs" (correlation_id);
CREATE INDEX "jobs_ix_download_jobs_priority" ON "jobs_download_jobs" (state, priority, created_at);
CREATE INDEX "jobs_ix_download_jobs_state_updated_at" ON "jobs_download_jobs" (state, updated_at);
CREATE INDEX "jobs_ix_download_jobs_status_updated_at" ON "jobs_download_jobs" (status, updated_at);
CREATE UNIQUE INDEX "jobs_ux_download_stage_attempt" ON "jobs_download_stage_attempts" (run_id, stage, artifact_key, attempt);
CREATE UNIQUE INDEX "jobs_ux_download_stage_attempt_dispatch" ON "jobs_download_stage_attempts" (dispatch_id);
CREATE INDEX "jobs_ix_download_worker_leases_status_expiry" ON "jobs_download_worker_leases" (status, expires_at);
CREATE INDEX "jobs_ix_playlist_items_playlist_id_index" ON "jobs_playlist_items" (playlist_id, playlist_index);
CREATE UNIQUE INDEX "jobs_ux_playlist_items_job_id" ON "jobs_playlist_items" (job_id);
CREATE UNIQUE INDEX "jobs_ux_playlist_items_playlist_id_entry_url" ON "jobs_playlist_items" (playlist_id, entry_url);
CREATE INDEX "jobs_ix_playlist_scan_entries_playlist_id_index" ON "jobs_playlist_scan_entries" (playlist_id, playlist_index);
CREATE INDEX "jobs_ix_playlists_correlation_id" ON "jobs_playlists" (correlation_id);
CREATE INDEX "jobs_ix_playlists_state_updated_at" ON "jobs_playlists" (state, updated_at);
CREATE UNIQUE INDEX "jobs_ux_playlists_source_url" ON "jobs_playlists" (source_url);
CREATE INDEX "jobs_ix_processed_messages_job_id" ON "jobs_processed_messages" (job_id);
CREATE INDEX "jobs_ix_processed_messages_operation_key" ON "jobs_processed_messages" (operation_key);
CREATE INDEX "media_ix_audio_encoding_status_account_encoded" ON "media_audio_encoding_status" (account_id, is_encoded);
CREATE INDEX "media_ix_audio_renditions_status" ON "media_audio_renditions" (status);
CREATE UNIQUE INDEX "media_ux_audio_renditions_media_version_storage" ON "media_audio_renditions" (media_guid, source_version_num, storage_key);
CREATE UNIQUE INDEX "media_ux_media_content_id_versions_media_guid_version_num" ON "media_media_content_id_versions" (media_guid, version_num);
CREATE UNIQUE INDEX "media_ux_media_content_id_versions_storage_key_content_hash" ON "media_media_content_id_versions" (storage_key, content_hash_xxh128);
CREATE INDEX "media_ix_media_source_versions_latest_job_id" ON "media_media_source_versions" (latest_job_id);
CREATE INDEX "media_ix_media_source_versions_media_guid" ON "media_media_source_versions" (media_guid);
CREATE INDEX "media_ix_media_source_versions_provider_source_media_id" ON "media_media_source_versions" (provider, source_media_id);
CREATE INDEX "media_ix_stream_renditions_status" ON "media_stream_renditions" (status);
CREATE UNIQUE INDEX "media_ux_stream_renditions_media_version_storage" ON "media_stream_renditions" (media_guid, source_version_num, storage_key);
CREATE INDEX "media_ix_user_media_likes_owner_liked_at" ON "media_user_media_likes" (owner_subject, liked_at);
CREATE INDEX "media_ix_watch_states_completed_watched_at" ON "media_watch_states" (completed, watched_at) WHERE ((completed = 1) AND (watched_at IS NOT NULL));
CREATE INDEX "metadata_ix_account_external_ids_account_id" ON "metadata_account_external_ids" (account_id);
CREATE UNIQUE INDEX "metadata_ux_account_external_ids_platform_value" ON "metadata_account_external_ids" (platform, external_id);
CREATE UNIQUE INDEX "metadata_ux_accounts_platform_handle" ON "metadata_accounts" (platform, account_handle);
CREATE UNIQUE INDEX "metadata_ux_artists_artist_name" ON "metadata_artists" (artist_name);
CREATE UNIQUE INDEX "metadata_ix_audio_stream_details_media_stream_id" ON "metadata_audio_stream_details" (media_stream_id);
CREATE UNIQUE INDEX "metadata_ux_cast_members_cast_name" ON "metadata_cast_members" (cast_name);
CREATE UNIQUE INDEX "metadata_ux_categories_category_name" ON "metadata_categories" (category_name);
CREATE INDEX "metadata_ix_chapter_data_media_base_id" ON "metadata_chapter_data" (media_base_id);
CREATE UNIQUE INDEX "metadata_ux_genres_genre_name" ON "metadata_genres" (genre_name);
CREATE UNIQUE INDEX "metadata_ix_media_base_media_guid" ON "metadata_media_base" (media_guid);
CREATE INDEX "metadata_ix_media_captions_media_lang_type" ON "metadata_media_captions" (media_guid, two_digit_language_code, caption_type);
CREATE INDEX "metadata_ix_media_comments_comment_id" ON "metadata_media_comments" (comment_id);
CREATE INDEX "metadata_ix_media_comments_media_time" ON "metadata_media_comments" (media_guid, comment_timestamp);
CREATE INDEX "metadata_ix_media_comments_parent_id" ON "metadata_media_comments" (parent_comment_id);
CREATE UNIQUE INDEX "metadata_ix_media_format_details_media_base_id" ON "metadata_media_format_details" (media_base_id);
CREATE INDEX "metadata_ix_media_metadata_account_id" ON "metadata_media_metadata" (account_id);
CREATE UNIQUE INDEX "metadata_ux_media_metadata_media_guid" ON "metadata_media_metadata" (media_guid);
CREATE INDEX "metadata_ix_media_streams_media_base_id" ON "metadata_media_streams" (media_base_id);
CREATE UNIQUE INDEX "metadata_ux_music_metadata_media_guid" ON "metadata_music_metadata" (media_guid);
CREATE UNIQUE INDEX "metadata_ux_series_metadata_media_guid" ON "metadata_series_metadata" (media_guid);
CREATE UNIQUE INDEX "metadata_ux_tags_tag_name" ON "metadata_tags" (tag_name);
CREATE UNIQUE INDEX "metadata_ix_video_stream_details_media_stream_id" ON "metadata_video_stream_details" (media_stream_id);
CREATE INDEX "notes_ix_user_notes_note_trgm" ON "notes_user_notes" (note);
CREATE INDEX "notes_ix_user_notes_owner_updated_at" ON "notes_user_notes" (owner_subject, updated_at);
CREATE UNIQUE INDEX "notes_ux_user_notes_owner_target" ON "notes_user_notes" (owner_subject, target_type, target_id);
CREATE INDEX "playlists_ix_media_playlist_membership_media_guid" ON "playlists_media_playlist_membership" (media_guid);
CREATE UNIQUE INDEX "playlists_ux_media_playlist_membership_playlist_id_index" ON "playlists_media_playlist_membership" (playlist_id, playlist_index);
CREATE UNIQUE INDEX "playlists_ux_metadata_playlist_metadata_playlist_id" ON "playlists_playlist_metadata" (playlist_id);
CREATE UNIQUE INDEX "playlists_ux_user_playlist_items_playlist_media" ON "playlists_user_playlist_items" (playlist_id, media_guid);
CREATE UNIQUE INDEX "playlists_ux_user_playlist_items_playlist_position" ON "playlists_user_playlist_items" (playlist_id, "position");
CREATE INDEX "playlists_ix_user_playlists_owner_created_at" ON "playlists_user_playlists" (owner_subject, created_at);
CREATE INDEX "scheduling_ix_scheduled_tasks_next_due_at" ON "scheduling_scheduled_tasks" (next_due_at);
CREATE UNIQUE INDEX "scheduling_uq_scheduled_tasks_key" ON "scheduling_scheduled_tasks" (key);
CREATE INDEX "statistics_ix_account_daily_states_account_id" ON "statistics_account_daily_states" (account_id);
CREATE INDEX "statistics_ix_channel_media_downloads_account_completed_at" ON "statistics_channel_media_downloads" (account_id, completed_at);
CREATE INDEX "statistics_ix_channel_media_downloads_media_guid_completed_at" ON "statistics_channel_media_downloads" (media_guid, completed_at);
CREATE INDEX "statistics_ix_creator_source_daily_states_creator_source_id" ON "statistics_creator_source_daily_states" (creator_source_id);
CREATE UNIQUE INDEX "storage_uq_storage_keys_key" ON "storage_storage_keys" (key);
